/* eslint-disable @next/next/no-html-link-for-pages */
import { navigation, plans } from "./site-data";
import { MobileMenu } from "./interactive";

export function Logo() { return <a href="/" className="logo" aria-label="CMSV6 home"><span className="logo-mark">C6</span><span><b>CMSV6</b><small>by iCustodian®</small></span></a>; }

export function Header() {
  return <><div className="offer-bar"><span>Compatible iCustodian® DVR purchase?</span> Get two months of CMSV6 hosting free. <a href="/pricing#free-offer">See offer</a></div><header className="site-header"><div className="container nav-row"><Logo/><nav className="desktop-nav" aria-label="Primary navigation">{navigation.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><div className="header-actions"><a className="login-link" href="/support#login">Customer login</a><a className="button primary small-button" href="/contact?enquiry=activation">Get CMSV6</a></div><MobileMenu/></div></header></>;
}

export function Footer() {
  return <footer className="footer"><div className="container footer-grid"><div><Logo/><p>UK-hosted remote CCTV, live-video, audio and GPS monitoring for compatible equipment.</p><div className="contact-lines"><a href="tel:+447543025555">+44 (0) 7543 02 5555</a><a href="mailto:info@icustodian.com">info@icustodian.com</a><span>Holly Hill Road, Erith, Greater London</span></div></div><div><h3>Explore</h3><a href="/features">Features</a><a href="/solutions">Solutions</a><a href="/equipment">Compatible equipment</a><a href="/pricing">Hosting prices</a><a href="/resources">Resources</a></div><div><h3>Help</h3><a href="/support">Support</a><a href="/faq">FAQs</a><a href="/contact">Contact & quotes</a><a href="https://www.icustodian.com/?utm_source=cmsv6.co.uk&utm_medium=referral&utm_campaign=cmsv6_equipment" rel="noreferrer">Shop iCustodian</a></div><div><h3>Responsible use</h3><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/responsible-use">Responsible CCTV use</a><p className="legal-note">Legal documents are provided as publication-ready placeholders and require review by a qualified UK legal or data-protection professional.</p></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} iCustodian Limited. CMSV6 and iCustodian are used as product and service marks.</span><span>CMSV6 is not an emergency-response service.</span></div></footer>;
}

export function SectionHeading({eyebrow, title, text, light=false}:{eyebrow:string;title:string;text:string;light?:boolean}) { return <div className={`section-heading ${light ? "light" : ""}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>; }

export function PricingCards() { return <div className="pricing-grid">{plans.map(plan => <article key={plan.months} className={`price-card ${plan.popular ? "popular" : ""}`}>{plan.popular && <span className="popular-tag">Most popular</span>}<span className="term">{plan.months}</span><div className="price"><span>£</span>{plan.price}</div><p>{plan.note}</p><ul><li>CMSV6 server hosting</li><li>One compatible device</li><li>Remote platform access</li><li>UK-based setup support</li></ul><a className={`button ${plan.popular ? "primary" : "dark"}`} href={`/contact?plan=${plan.months.replace(" ", "-")}`}>{plan.cta}</a></article>)}</div>; }

export function CTA({title="Ready to see what matters?", text="Tell us about your vehicle, property, farm, boat or multi-site operation. We’ll help you check compatibility and choose the right route.", secondary=true}:{title?:string;text?:string;secondary?:boolean}) { return <section className="cta-band"><div className="container cta-inner"><div><span className="eyebrow">Talk to a CMSV6 specialist</span><h2>{title}</h2><p>{text}</p></div><div className="cta-actions"><a className="button light" href="/contact">Start an enquiry</a>{secondary && <a className="button outline-light" href="https://www.icustodian.com/product-category/dvr/?utm_source=cmsv6.co.uk&utm_medium=referral&utm_campaign=cmsv6_equipment" rel="noreferrer">View compatible DVRs</a>}</div></div></section>; }

export function Disclaimer() { return <div className="disclaimer"><strong>Compatibility matters.</strong><p>Features depend on the connected DVR, cameras, sensors, firmware, account permissions and configuration. Live access and GPS reporting require suitable internet and, where relevant, GPS coverage. Standard hosting does not automatically include mobile data, hardware, installation or server-side video storage.</p></div>; }
