export const legalDocuments = {
  terms: String.raw`# TERMS OF USE AND CMSV6 SERVICE TERMS

**Last updated: 2 August 2026**

## 1. About These Terms

These Terms of Use and CMSV6 Service Terms govern access to and use of:

* The cmsv6.co.uk website
* The iCustodian® CMSV6 CCTV Live Video GPS Streaming Service
* CMSV6 customer accounts
* CMSV6 server-hosting subscriptions
* Remote video, audio and GPS monitoring functions
* Related applications and software
* Device activation services
* Technical support
* Associated services supplied by iCustodian

Please read these Terms carefully before using the website, purchasing a subscription, activating a device or accessing CMSV6.

By accessing the website, placing an order, accepting a quotation, registering an account, activating a device or using any part of CMSV6, you confirm that you have read, understood and agreed to these Terms.

If you do not agree to these Terms, you must not use CMSV6.

---

## 2. About iCustodian

The cmsv6.co.uk website and the iCustodian® CMSV6 service are owned and operated by:

**iCustodian Limited**
Trading as **iCustodian®**

**Company number:** 15930836
**Registered office:** 18 Holly Hill Road, Erith, England, DA8 1QD, United Kingdom
**Email:** [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)
**Website:** cmsv6.co.uk

iCustodian Limited is registered with the Information Commissioner’s Office.

ICO registration does not mean that the Information Commissioner’s Office has approved, certified, recommended or endorsed CMSV6 or any iCustodian product.

References in these Terms to “iCustodian”, “CMSV6”, “we”, “us” or “our” mean iCustodian Limited.

References to “you”, “your”, “Customer” or “User” mean the individual, business, organisation, public authority or other entity accessing or using the Services.

---

## 3. Definitions

### Account

A CMSV6 administrator, customer or Authorised User account.

### Authorised User

A person whom the Customer has lawfully authorised to access its CMSV6 Account or connected Devices.

### Compatible Device

A DVR, MDVR, camera system, GPS-enabled device, sensor or related product confirmed as compatible with the relevant CMSV6 service.

### Customer Content

Video, images, audio, GPS locations, routes, alarm events, vehicle information, device information, uploaded files and other information transmitted through or generated by a Customer’s connected Device.

### Device

A DVR, MDVR, camera system, GPS unit, vehicle recorder or other compatible equipment connected or intended to be connected to CMSV6.

### Services

The website, CMSV6 platform, server-hosting service, remote-access functions, applications, software, support and related services supplied by iCustodian.

### Subscription

A paid or promotional right to connect a particular Device to CMSV6 for an agreed period.

---

## 4. Description of CMSV6

CMSV6 is a remote CCTV, live-video, audio, GPS and device-management platform for compatible equipment.

Depending on the connected equipment, configuration, permissions and network connection, CMSV6 may provide:

* Live remote video
* Multi-camera viewing
* GPS location monitoring
* Historical route playback
* Local or remote video playback
* Remote footage requests
* Video and image downloads
* Snapshots
* Audio monitoring
* Two-way voice communication
* Device-status information
* Alarm and event information
* Geofences
* Journey and device reports
* Camera-channel management
* Device groups
* User permissions
* PTZ camera controls
* Remote configuration
* Driver-safety information
* Sensor information
* Compatible AI-assisted functions

Not every Device supports every feature.

The features available depend on matters including:

* Device manufacturer and model
* Firmware version
* Installed cameras
* Microphones and speakers
* GPS hardware
* Sensors
* Storage configuration
* Mobile or internet connection
* CMSV6 account configuration
* Permissions
* Purchased licences
* Subscription type

A feature described on our website or demonstrated in CMSV6 is not guaranteed to be available on every Device.

You must check compatibility before purchasing or relying on a specific function.

---

## 5. Vehicle and Fixed-Site Use

CMSV6 may be used with compatible equipment in moving vehicles, fixed premises, remote sites and other lawful environments.

Possible applications include:

* Private vehicles
* Taxis and private-hire vehicles
* Vans, lorries and HGVs
* Delivery and haulage fleets
* Buses, coaches and minibuses
* Emergency vehicles
* Heavy plant and agricultural machinery
* Boats and marine vessels
* Homes
* Offices
* Shops
* Warehouses
* Factories
* Farms
* Schools
* Healthcare premises
* Care facilities
* Construction sites
* Temporary locations

Technical capability does not mean that every possible use is lawful, appropriate or proportionate.

You are responsible for assessing the legality and suitability of your installation.

---

## 6. UK Hosting and International Customers

The core CMSV6 server-hosting service supplied by iCustodian is hosted in the United Kingdom.

We may offer CMSV6 to Customers in the United Kingdom and other countries.

International Customers are responsible for ensuring that their use complies with all laws and requirements applicable in their country, including laws concerning:

* CCTV
* Video recording
* Audio recording
* Location tracking
* Employee monitoring
* Passenger recording
* Data protection
* Telecommunications
* Transport
* Safeguarding
* Cross-border data transfers
* Licensing
* Surveillance

We do not represent that CMSV6 is lawful, appropriate or available for every purpose in every country.

We may refuse or discontinue service in a country where providing CMSV6 would expose us to legal, regulatory, sanctions, security or operational risks.

---

## 7. Eligibility and Authority

You must be at least 18 years old to purchase a Subscription or administer a CMSV6 Account.

Where you use CMSV6 for a company, organisation, charity, school, public authority or other entity, you confirm that:

* You are authorised to act for that entity.
* You have authority to accept these Terms.
* You have authority to connect the relevant Devices.
* You have authority to appoint Authorised Users.
* The entity agrees to be bound by these Terms.

You must not create an Account using false, misleading or unauthorised information.

---

## 8. Account Registration

You may be required to provide:

* Your name
* Company or organisation name
* Email address
* Telephone number
* Billing information
* Service address
* Device model
* Device identifier
* Vehicle or site information
* Technical details required for activation

All information supplied must be accurate, complete and current.

We may delay or refuse activation where information is incomplete, inaccurate, suspicious or cannot reasonably be verified.

---

## 9. Account Security

You are responsible for protecting:

* Usernames
* Passwords
* Administrator credentials
* Verification codes
* Device credentials
* Mobile applications
* Computers and phones used to access CMSV6
* Authorised User accounts

You must:

* Use strong and unique passwords.
* Change default passwords promptly.
* Prevent unauthorised access.
* Restrict administrator access.
* Remove users who no longer require access.
* Protect computers and mobile devices.
* notify us promptly of suspected compromise.
* Avoid sharing credentials between multiple users.
* Keep supported applications and Devices reasonably up to date.

You are responsible for activities performed through your Account unless they result directly from our breach or failure to use reasonable security measures.

We may suspend an Account where we reasonably suspect unauthorised access or misuse.

---

## 10. Authorised Users

A business or organisational Customer may provide access to employees, contractors, administrators and other authorised personnel.

The Customer is responsible for:

* Selecting Authorised Users.
* Assigning appropriate permissions.
* Supervising users.
* Removing unnecessary access.
* Ensuring compliance with these Terms.
* Preventing personal or unauthorised use of footage.
* Maintaining appropriate access records.

Actions taken by an Authorised User may be treated as actions of the Customer.

You must not give access to anyone who does not have a lawful and legitimate reason to use CMSV6.

---

## 11. Device Compatibility

CMSV6 works only with compatible equipment.

Compatibility may depend on:

* Manufacturer
* Model
* Firmware
* Device protocol
* Serial number
* Server settings
* Camera format
* GPS equipment
* SIM configuration
* Sensors
* Licences
* Accessories

A Device may support some CMSV6 functions without supporting all functions.

A compatibility check is based on the information available at the time and does not guarantee that every feature will operate in every environment.

We are not responsible for inaccurate information supplied by a Customer, manufacturer, installer, seller or other third party.

---

## 12. Installation

You are responsible for ensuring that Devices, cameras, microphones, antennas, storage media, routers, sensors and accessories are installed safely and correctly.

Vehicle equipment must not:

* Obstruct the driver’s view.
* Interfere with airbags or controls.
* Create unsafe wiring.
* Distract the driver.
* Encourage live viewing while driving.
* Breach vehicle or licensing requirements.

Cameras must not be positioned in locations where monitoring is unlawful, unjustified or unreasonably intrusive.

Professional installation is recommended where electrical, vehicle, marine, agricultural or building work is required.

Unless separately agreed, CMSV6 hosting does not include:

* Physical installation
* Camera installation
* Vehicle wiring
* SIM cards
* Mobile data
* Local storage media
* Equipment repair
* On-site support

---

## 13. Connectivity Requirements

Remote CMSV6 features require a suitable internet connection.

Connectivity may be provided through:

* Mobile data
* A compatible SIM
* Wi-Fi
* Ethernet
* A supported router
* Another approved connection

You are responsible for:

* Obtaining an appropriate connection.
* Paying network and data charges.
* Selecting a suitable data allowance.
* Maintaining an active SIM or internet service.
* Checking coverage.
* Configuring the network correctly.
* Permitting roaming where required.

Service may be affected by:

* Poor mobile coverage
* Network congestion
* Buildings
* Tunnels
* Remote areas
* Marine environments
* Weather
* Power loss
* Data limits
* Network maintenance
* Third-party outages
* GPS signal obstruction

We do not guarantee continuous internet access, mobile coverage, GPS reception or uninterrupted live video.

---

## 14. Local Recording and Remote Access

With many compatible systems, continuous recordings are stored locally on the Device’s hard drive, SD card or other storage media.

CMSV6 may provide remote access to that Device.

A loss of internet connectivity may interrupt:

* Live viewing
* GPS updates
* Remote commands
* Remote playback
* Remote downloads
* Alarm notifications

Compatible DVRs may continue recording locally during an interruption, but this depends on the Device, installation, storage capacity, power supply and configuration.

You are responsible for checking local recording and storage regularly.

---

## 15. Customer Content and Server Processing

We do not claim ownership of Customer Content.

However, operating CMSV6 may require our systems to receive, transmit, process, buffer, cache or temporarily store:

* Live video
* Audio
* GPS coordinates
* Historical routes
* Device status
* Alarm events
* Snapshots
* Thumbnails
* Requested footage
* Downloaded files
* Connection logs
* Access logs
* Technical diagnostics

Unless a separate server-storage service is expressly purchased, permanent cloud storage of continuous CCTV recordings is not included.

We do not routinely watch customer cameras or monitor journeys.

Limited access to Customer Content may occur where reasonably necessary to:

* Provide authorised technical support
* Investigate a security incident
* Investigate credible unlawful use
* Maintain the Service
* Comply with law
* Protect a person from serious and immediate harm

---

## 16. Customer Data-Protection Responsibilities

The Customer normally decides:

* Why monitoring takes place.
* Where cameras are positioned.
* Whether audio is enabled.
* Whether GPS tracking is enabled.
* Who may view information.
* How information is used.
* How long it is retained.
* Whether it is disclosed.
* How individual rights requests are handled.

The Customer will usually be the data controller for its CCTV, audio and GPS monitoring.

Where we process Customer Content solely to provide CMSV6 on the Customer’s instructions, we will generally act as a data processor.

We may act as a data controller for our own:

* Account records
* Customer contact information
* Billing information
* Support records
* Security records
* Fraud-prevention activities
* Legal and regulatory compliance

Business Customers may be required to enter into a separate Data Processing Addendum.

---

## 17. Lawful Use

You may use CMSV6 only for lawful, legitimate and proportionate purposes.

Before using video, audio or GPS monitoring, you must consider whether you require:

* A lawful basis
* CCTV signs
* A privacy notice
* Employee or driver information
* Consent or other lawful authority
* A data-protection impact assessment
* A retention policy
* A safeguarding assessment
* Permission from the property owner
* Permission from the vehicle owner
* An employee-monitoring policy
* A procedure for access requests
* Appropriate security controls
* Local licences or approvals
* Registration with a relevant regulator

Our supply of equipment, hosting, activation or support does not confirm that your proposed use is lawful.

---

## 18. Prohibited Uses

You must not use CMSV6:

* For illegal surveillance.
* For spying.
* To stalk, harass, threaten or intimidate.
* To monitor a partner or former partner unlawfully.
* To facilitate domestic abuse or coercive control.
* To record intimate activity.
* To create voyeuristic content.
* To monitor children or vulnerable people unlawfully.
* In toilets, changing rooms or similarly private areas.
* To access another person’s Account without permission.
* To track a vehicle, person or asset without lawful authority.
* To monitor employees secretly without lawful justification.
* To record private conversations unlawfully.
* To commit or facilitate crime.
* To identify targets for theft, violence or exploitation.
* To interfere with emergency services.
* To impersonate another person or organisation.
* To introduce malware or harmful code.
* To probe, attack or overload the platform.
* To bypass security controls.
* To reverse engineer CMSV6 except where legally permitted.
* To resell CMSV6 without written permission.
* In breach of sanctions or export restrictions.
* As the sole method of protecting life or responding to emergencies.
* In a way that distracts a driver.

We may suspend or terminate suspected unlawful use immediately.

We may preserve and disclose relevant information where legally required or reasonably necessary to prevent serious harm.

---

## 19. Employee and Driver Monitoring

Customers monitoring workers, drivers or contractors must ensure that monitoring is:

* Lawful
* Necessary
* Proportionate
* Transparent
* Restricted to legitimate purposes
* Protected against misuse

CMSV6 must not be used for unjustified continuous surveillance.

Where a vehicle may be used privately, the Customer must consider whether private-use tracking should be restricted or disabled.

---

## 20. Audio Recording

Audio monitoring can be more intrusive than video-only monitoring.

You must not enable audio merely because the equipment supports it.

Before enabling audio, you must determine whether it is:

* Lawful
* Necessary
* Proportionate
* Properly disclosed
* Supported by an appropriate lawful basis
* Permitted by applicable licensing and employment requirements

We may refuse or disable support for audio where we reasonably believe the proposed use is unlawful or creates an unacceptable risk.

---

## 21. GPS Information

GPS information is approximate and may be affected by:

* Signal availability
* Antenna placement
* Equipment
* Delays
* Mapping information
* Network conditions
* Environmental obstruction

GPS information must not be treated as infallible.

You must have lawful authority to track the relevant vehicle, vessel, Device or asset.

---

## 22. AI and Driver-Safety Functions

Compatible equipment may offer:

* ADAS alerts
* Driver-status monitoring
* Fatigue warnings
* Lane-departure warnings
* Forward-collision warnings
* Object detection
* Blind-spot detection
* Passenger counting
* Other AI-assisted functions

These functions:

* Depend on compatible equipment.
* May generate false or delayed alerts.
* May fail to detect an event.
* Do not control the vehicle.
* Do not replace an attentive driver.
* Do not replace mirrors or direct observation.
* Do not guarantee accident prevention.
* Must not be the sole basis for disciplinary, insurance or legal decisions without human review.

---

## 23. No Emergency or Guaranteed Security Service

CMSV6 is a monitoring and remote-access platform.

It is not:

* An emergency service
* A police service
* A fire or ambulance service
* A guaranteed alarm-response service
* A vehicle-recovery service
* A medical-monitoring service
* A replacement for emergency calls
* A guarantee against theft, crime, damage, injury or loss

We do not continuously watch every connected camera or vehicle unless a separate written monitoring contract expressly states otherwise.

In an emergency, contact the appropriate emergency service directly.

---

## 24. Hosting Prices

CMSV6 hosting is generally charged per connected Device.

Standard published hosting periods are:

* **Six months: £60 per Device**
* **Twelve months: £100 per Device**
* **Twenty-four months: £180 per Device**

Longer periods and multi-device arrangements may be available by quotation.

The price applying to an order will be shown at checkout, on an invoice or in an accepted quotation.

Any applicable VAT or tax will be shown where required.

Unless expressly stated, hosting does not include:

* DVR hardware
* Cameras
* Installation
* SIM cards
* Mobile data
* Internet service
* Local storage
* Replacement equipment
* Permanent cloud-video storage
* On-site support
* Custom integration

---

## 25. Two-Month Free Hosting Offer

Every qualifying compatible iCustodian® DVR purchased directly through iCustodian includes two months of CMSV6 server hosting free of charge.

The offer:

* Applies only to qualifying Devices.
* Is attached to the qualifying Device.
* Requires successful compatibility and activation.
* Is intended for setup, testing and evaluation.
* Has no cash value.
* Cannot normally be exchanged.
* Does not include installation, SIM cards or mobile data.
* Does not guarantee support for every CMSV6 function.

At the end of the free period, the Customer must purchase a Subscription to continue using CMSV6.

The Service may be suspended when the free period expires if no paid plan is selected.

---

## 26. Orders and Activation

An order is accepted when we issue a written confirmation, invoice, activation confirmation or other clear acceptance.

We may reject or delay an order where:

* The Device is incompatible.
* Required information is incomplete.
* Payment has not been received.
* The proposed use appears unlawful.
* We cannot provide service in the relevant territory.
* The transaction presents a fraud or security risk.
* A technical dependency is unavailable.
* A price contains an obvious error.

Activation times are estimates unless confirmed otherwise in writing.

---

## 27. Payments

Charges must be paid by the date stated at checkout, on an invoice or in a quotation.

Where payment is overdue, reversed, declined or charged back, we may:

* Delay activation
* Suspend CMSV6
* Refuse renewal
* Recover outstanding amounts
* Terminate the affected Subscription

Nothing prevents a Customer from disputing an unauthorised or incorrect charge lawfully.

---

## 28. Renewals

Your order confirmation will state whether a Subscription:

* Expires at the end of its fixed term; or
* Renews automatically

We will not treat a Subscription as automatically renewable unless this was clearly disclosed and agreed.

For fixed-term plans, you are responsible for renewing before expiry.

We may send reminders but cannot guarantee that a reminder will be received.

---

## 29. Consumer Cancellation Rights

This section applies where you are acting as a consumer.

Where required by law, you may have a 14-day right to cancel a distance service contract.

If you request activation during the cancellation period:

* You expressly request early performance.
* You may have to pay for the service supplied before cancellation.
* You may lose the cancellation right once the service has been fully performed where the legal requirements have been satisfied.

To request cancellation, email [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk).

Nothing in these Terms removes consumer rights that cannot legally be excluded.

Business Customers do not receive consumer cancellation rights unless agreed in writing.

---

## 30. Refunds

Refunds will be provided where required by law or agreed in writing.

Subject to statutory rights, prepaid hosting fees are generally non-refundable after activation, except where:

* We cannot supply the purchased Service.
* We materially breach the agreement and fail to remedy it.
* A refund is legally required.
* We agree otherwise in writing.

A refund is not normally due where a problem results from:

* Poor mobile coverage
* Insufficient data allowance
* Customer installation
* Incorrect Customer configuration
* Unsupported third-party equipment
* Failure to use the Service
* Customer cancellation of an active business plan
* Suspension for serious unlawful use

---

## 31. Support

We will provide reasonable remote support through the channels we make available.

Unless separately agreed, support does not include:

* Guaranteed 24-hour response
* Continuous monitoring
* On-site attendance
* Vehicle or electrical repair
* Third-party equipment repair
* Mobile-network support
* Recovery of deleted footage
* Forensic evidence services
* Legal advice
* Data-protection advice
* Emergency response

We may request screenshots, logs, Device information or authorised temporary access to investigate a problem.

---

## 32. Maintenance and Changes

We may maintain, update, replace or modify the platform for:

* Security
* Legal compliance
* Compatibility
* Performance
* Reliability
* Abuse prevention
* Third-party changes
* Obsolescence

We will try to minimise disruption where reasonably possible.

Business service levels apply only where included in a separate written service-level agreement.

---

## 33. Availability

We will provide the Service with reasonable care and skill.

We do not guarantee that it will always be:

* Uninterrupted
* Error free
* Available in every location
* Compatible with every network
* Free from delays
* Free from third-party outages
* Able to recover every recording
* Suitable for every intended purpose

You must maintain appropriate alternative arrangements for important operations.

Important footage should be downloaded and preserved promptly.

CMSV6 must not be treated as the only permanent archive unless a separate storage agreement confirms otherwise.

---

## 34. Suspension

We may suspend all or part of CMSV6 where:

* Payment is overdue.
* A Subscription has expired.
* We suspect unauthorised access.
* The Account creates a security risk.
* A Device is harming the platform.
* The Service is being used unlawfully.
* These Terms have been breached.
* Suspension is legally required.
* Suspension is necessary to protect another person.
* Required information has not been provided.

Immediate suspension may occur where there is a serious risk involving stalking, abuse, unlawful surveillance, crime or system compromise.

---

## 35. Termination

You may stop using CMSV6 or terminate a Subscription in accordance with your order terms.

We may terminate where:

* You seriously or repeatedly breach these Terms.
* CMSV6 is used unlawfully.
* Payment remains outstanding.
* Continued service would be unlawful.
* The Account creates a serious security risk.
* A remediable breach is not corrected.
* A required technical dependency ends.
* The relevant Service is permanently discontinued.

Where we discontinue a prepaid Service for our own commercial reasons and you have not breached these Terms, we will provide an appropriate pro-rata refund for the unused period unless an equivalent replacement is accepted.

---

## 36. Effect of Termination

When a Subscription ends:

* CMSV6 access may be disabled.
* Devices may stop reporting.
* Live viewing may stop.
* GPS functions may stop.
* Authorised Users may lose access.
* Server-side information may be deleted under our retention practices.
* Local Device recordings may remain subject to the Device’s storage configuration.

You must not rely on us to retain Customer Content after termination.

---

## 37. Intellectual Property

The website, software, documentation, graphics, designs, text, databases, branding and related materials are protected by intellectual-property laws.

Subject to payment and compliance with these Terms, we grant you a limited, non-exclusive, non-transferable and revocable right to use CMSV6 for lawful internal purposes during the active Subscription.

You must not:

* Copy or redistribute the software unlawfully.
* Remove intellectual-property notices.
* Present CMSV6 as your own service.
* Use our branding without permission.
* Resell CMSV6 without authorisation.
* Extract protected elements to create a competing service.
* Attempt to obtain source code except where legally permitted.

Customer Content remains owned by the Customer or its lawful owner.

---

## 38. Third-Party Services

CMSV6 may rely on third parties providing:

* Mapping
* Mobile networks
* Internet access
* Device hardware
* Applications
* Payment processing
* Hosting infrastructure
* Notifications
* Operating systems

Third-party services may have separate terms.

We are not responsible for a third party’s independent actions, outages, coverage, pricing, content or legal compliance.

---

## 39. Security

We use reasonable technical and organisational security measures appropriate to the Service.

No internet-connected system is completely secure.

You acknowledge risks including:

* Password compromise
* Device theft
* Malware
* Customer misconfiguration
* Outdated firmware
* Insecure third-party hardware
* Employee misuse
* Network interception
* Unauthorised access

Suspected security incidents must be reported promptly to [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk).

---

## 40. Customer Warranties

You confirm that:

* You have authority to use the connected equipment.
* You have a lawful reason for monitoring.
* Camera placement is lawful.
* Appropriate notices have been provided.
* Audio will be used only where lawful.
* GPS tracking will be authorised.
* Login details will be protected.
* CMSV6 will not be used for spying or stalking.
* Applicable laws will be followed.
* Information supplied to us is accurate.
* Another person’s rights will not be infringed.

---

## 41. Liability to Consumers

Where you are a consumer, we are responsible for foreseeable loss caused by our breach or failure to use reasonable care and skill.

We are not responsible for loss that was not reasonably foreseeable.

Nothing in these Terms excludes:

* Liability that cannot legally be excluded
* Statutory consumer rights
* Liability for death or personal injury caused by negligence
* Fraud or fraudulent misrepresentation

---

## 42. Liability to Business Customers

This section applies to business and organisational Customers.

To the maximum extent legally permitted, we are not liable for:

* Loss of profit
* Loss of revenue
* Loss of business
* Loss of contracts
* Loss of opportunity
* Loss of anticipated savings
* Loss of goodwill
* Business interruption
* Indirect or consequential loss
* Mobile-network failure
* GPS failure
* Unsupported equipment
* Customer installation
* Unlawful Customer use
* Footage the Customer failed to preserve
* Decisions made solely from an automated alert
* Events CMSV6 was not designed to prevent

Subject to liabilities that cannot legally be limited, our total aggregate liability connected with an affected Service during a 12-month period will not exceed the fees paid or payable for that affected Service during the preceding 12 months.

---

## 43. Business Customer Indemnity

A business or organisational Customer will be responsible for reasonable losses, liabilities and third-party claims suffered by us as a direct result of:

* Unlawful surveillance by the Customer
* Unlawful recording or tracking
* Serious breach of data-protection law
* Failure to obtain required permissions
* Customer Content that is unlawful
* Use of CMSV6 for stalking, harassment or abuse
* Material breach of the prohibited-use rules

This does not apply to the extent that the claim was caused by our own breach, negligence or unlawful conduct.

---

## 44. Events Outside Our Control

We are not responsible for delay or failure caused by circumstances outside our reasonable control, including:

* Natural disasters
* Fire or flood
* Severe weather
* War
* Terrorism
* Government action
* Sanctions
* Power failures
* Mobile-network failures
* Internet failures
* Cyberattacks despite reasonable precautions
* Data-centre failures
* Supply-chain disruption
* Device-manufacturer changes
* App-store restrictions
* GPS-system disruption

---

## 45. Changes to Prices and Terms

We may change prices for future purchases and renewals.

A price change will not normally alter an active prepaid fixed-term Subscription.

We may update these Terms to reflect:

* Service changes
* Security requirements
* Legal changes
* Regulatory requirements
* New features
* Business changes
* Clarifications

Material changes affecting an active paid Subscription will be communicated where reasonably required.

---

## 46. Privacy

Our processing of personal information is explained in the CMSV6 Privacy Policy.

Additional data-processing terms may apply where we process Customer Content on behalf of a business Customer.

---

## 47. Complaints

Complaints should be sent to:

**Email:** [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)

Please include:

* Your name
* Account information
* Order or invoice number
* Device identifier where relevant
* A description of the issue
* The outcome requested

Nothing prevents a consumer from exercising statutory rights or contacting an appropriate regulator or court.

---

## 48. Governing Law

These Terms are governed by the laws of England and Wales.

Business disputes will be subject to the exclusive jurisdiction of the courts of England and Wales unless agreed otherwise.

Consumers may retain mandatory rights to bring proceedings in the part of the United Kingdom or country where they live.

---

## 49. Contact Details

**iCustodian Limited**
Trading as **iCustodian®**

**Company number:** 15930836
**Registered office:** 18 Holly Hill Road, Erith, England, DA8 1QD, United Kingdom
**ICO registration:** iCustodian Limited is registered with the Information Commissioner’s Office
**Email:** [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)
**Website:** cmsv6.co.uk`,
  privacy: String.raw`# CMSV6 PRIVACY POLICY

**Last updated: 2 August 2026**

## 1. Introduction

This Privacy Policy explains how iCustodian Limited collects, uses, stores, shares and protects personal information in connection with:

* The cmsv6.co.uk website
* The iCustodian® CMSV6 CCTV Live Video GPS Streaming Service
* Customer Accounts
* Device activations
* Server-hosting subscriptions
* Orders and payments
* Customer enquiries
* Technical support
* Remote video, audio and GPS functions
* Related software and applications

We are committed to handling personal information lawfully, fairly, transparently and securely.

This Privacy Policy should be read with our:

* Terms of Use and CMSV6 Service Terms
* Cookie Policy
* Acceptable Use Policy
* Responsible CCTV Use information
* Data Processing Addendum where applicable
* Any service-specific privacy notice

This Privacy Policy does not replace a separate CCTV or employee-monitoring privacy notice that a CMSV6 Customer may be required to provide to drivers, employees, passengers, visitors, residents, pupils, patients or other recorded individuals.

---

## 2. Who We Are

The cmsv6.co.uk website and the iCustodian® CMSV6 service are operated by:

**iCustodian Limited**
Trading as **iCustodian®**

**Company number:** 15930836
**Registered office:** 18 Holly Hill Road, Erith, England, DA8 1QD, United Kingdom
**Email:** [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)
**Website:** cmsv6.co.uk

iCustodian Limited is registered with the Information Commissioner’s Office.

Our ICO registration does not mean that the Information Commissioner’s Office has approved, certified or endorsed CMSV6 or any iCustodian product.

References to “iCustodian”, “CMSV6”, “we”, “us” or “our” mean iCustodian Limited.

---

## 3. Scope of This Policy

This Privacy Policy applies to personal information processed about:

* Website visitors
* Prospective Customers
* Private Customers
* Business Customers
* Customer representatives
* Account administrators
* Authorised Users
* Installers
* Technical contacts
* Suppliers
* Business partners
* People contacting support
* People making privacy requests or complaints

CMSV6 may also process video, images, audio, GPS locations, routes and device information collected through a Customer’s compatible equipment.

Our role in relation to that information is explained below.

---

## 4. Our Data-Protection Roles

### 4.1 When We Are the Data Controller

We normally act as the data controller for personal information used to manage our own business.

This includes information used for:

* Enquiries
* Quotations
* Customer Accounts
* Orders
* Payments
* Subscriptions
* Device activation
* Customer relationships
* Technical support
* Website security
* Fraud prevention
* Service communications
* Complaints
* Legal compliance
* Marketing where permitted

As controller, we decide why and how this information is processed.

### 4.2 When We Are a Data Processor

Where a business, school, care organisation, fleet operator, transport provider, public authority or other Customer uses CMSV6 for its own CCTV, audio or GPS purposes, that Customer will usually be the data controller.

In those circumstances, iCustodian will generally act as a data processor when processing Customer Content only:

* To provide CMSV6
* On the Customer’s documented instructions
* To maintain security
* To provide authorised support
* To comply with applicable law

The Customer decides:

* Why cameras are installed
* Where cameras are positioned
* Who is monitored
* Whether audio is enabled
* Whether GPS is enabled
* Who may view the information
* How the information is used
* How long it is retained
* Whether it is disclosed
* How individual rights requests are handled

A separate Data Processing Addendum may apply.

### 4.3 Our Role Depends on the Activity

Our legal role is determined by the actual processing activity.

We may be a controller for one activity and a processor for another.

We do not use Customer Content for unrelated advertising, profiling or commercial exploitation.

---

## 5. CCTV, Video and GPS Information

CMSV6 is primarily a remote-access, live-viewing, GPS and device-management platform.

With many compatible systems:

* Continuous recordings remain on the Customer’s DVR or local storage.
* CMSV6 provides authorised remote access.
* Live video may pass through CMSV6 infrastructure.
* GPS and device information may be transmitted to CMSV6 servers.
* Customers may request snapshots, playback or footage downloads.
* Certain clips, images or events may be stored where configured.

We do not claim ownership of Customer Content.

We do not routinely watch Customer cameras or monitor Customer journeys.

However, operating CMSV6 may require our systems to receive, transmit, process, buffer, cache or temporarily store:

* Live video streams
* Audio streams
* Camera images
* Snapshots
* Video clips
* Requested recordings
* GPS coordinates
* Historical routes
* Vehicle information
* Device identifiers
* Device status
* Alarm information
* Event information
* Connection logs
* Access logs
* Technical diagnostics

Permanent server storage of continuous CCTV recordings is not included unless expressly purchased, configured and confirmed.

---

## 6. Personal Information We Collect

### 6.1 Identity and Contact Information

We may collect:

* Full name
* Business or organisation name
* Job title
* Postal address
* Service address
* Billing address
* Email address
* Telephone number
* Preferred contact method
* Customer number

### 6.2 Account Information

We may collect:

* Username
* Protected authentication information
* Account role
* Administrator status
* User permissions
* Account creation date
* Login activity
* Password-reset activity
* Authentication events
* Account preferences
* Subscription status

Properly protected passwords should not be available to us in plain text.

### 6.3 Orders, Subscriptions and Payments

We may collect:

* Products and services ordered
* Hosting period
* Device quantity
* Price
* Invoice details
* Payment status
* Transaction references
* Refund information
* Renewal date
* Expiry date
* Tax information where applicable

Full payment-card information may be collected directly by an independent payment provider.

We will normally receive limited information such as:

* Payment confirmation
* Transaction reference
* Card type
* Limited card digits
* Billing information
* Payment status

We do not intend to retain complete card security codes.

### 6.4 Device and Technical Information

We may collect:

* Device manufacturer
* Device model
* Serial number
* Device ID
* SIM-related configuration information
* Firmware version
* Camera-channel information
* Storage configuration
* GPS status
* Network status
* IP address
* Connection status
* Device online or offline status
* Device time and time zone
* Activation date
* Server assignment
* Technical settings
* Sensor information
* Error messages
* Diagnostic records

### 6.5 Website Information

When you use our website, we may collect:

* IP address
* Browser
* Device type
* Operating system
* Screen size
* Language
* General location derived from IP address
* Pages visited
* Visit dates and times
* Referring website
* Links selected
* Session information
* Cookie preferences
* Website errors
* Security events
* Login attempts

Non-essential analytics or advertising technologies will be used only in accordance with our Cookie Policy and applicable consent requirements.

### 6.6 Enquiry and Support Information

We may collect:

* Contact-form information
* Compatibility-check details
* Support requests
* Complaints
* Emails
* Chat messages
* Screenshots
* Technical photographs
* Device logs
* Installation details
* Telephone-call information
* Information required to investigate an issue

If a telephone call is recorded, an appropriate notice will be provided.

Please do not send unnecessary footage, private conversations, medical information or other sensitive material unless we request it through an appropriate method.

### 6.7 Marketing Information

We may collect:

* Marketing preferences
* Consent records
* Product interests
* Previous enquiries
* Email engagement information
* Objections
* Unsubscribe requests

### 6.8 Customer Content

Depending on the installation, Customer Content may include:

* Images of identifiable people
* Voices
* Vehicle registration numbers
* Driver information
* Passenger information
* Employee information
* Visitor information
* GPS coordinates
* Routes and stops
* Speed information
* Alarm events
* Dates and times
* Location history
* Road-facing footage
* Vehicle-interior footage
* Footage from homes or businesses
* Farm or marine footage
* Sensor information

Customer Content may incidentally reveal sensitive information such as:

* Health
* Disability
* Racial or ethnic origin
* Religious beliefs
* Trade union activity
* Sexual orientation
* Alleged criminal behaviour

The Customer is responsible for ensuring that collecting this information is lawful, necessary and proportionate.

---

## 7. How We Obtain Information

We may obtain personal information:

### Directly from You

When you:

* Submit an enquiry
* Request a quotation
* Purchase a product
* Buy hosting
* Create an Account
* Activate a Device
* Contact support
* Submit a complaint
* Subscribe to marketing

### From Your Employer or Organisation

A Customer may provide your information when:

* Creating an Authorised User
* Appointing an administrator
* Naming a billing contact
* Requesting support
* Authorising Device management

### From Connected Devices

Compatible Devices may transmit:

* Device information
* GPS information
* Status information
* Technical events
* Live streams
* Requested recordings
* Snapshots
* Alarm information

### From Service Providers

We may receive limited information from:

* Payment providers
* Delivery companies
* Email providers
* Hosting providers
* Analytics services
* Fraud-prevention providers
* Technical providers

### From Public Sources

For business verification, fraud prevention or legal purposes, we may obtain information from:

* Companies House
* Business websites
* Professional directories
* Public registers

---

## 8. Why We Use Information

### 8.1 Enquiries and Quotations

We use information to:

* Respond to enquiries
* Prepare quotations
* Check compatibility
* Recommend services
* Arrange demonstrations

Lawful bases:

* Steps requested before entering a contract
* Performance of a contract
* Legitimate interests in responding to enquiries

### 8.2 Accounts and Subscriptions

We use information to:

* Create Accounts
* Activate Devices
* Provide hosting
* Manage subscriptions
* Provide access
* Send renewal notices
* Maintain service records

Lawful bases:

* Performance of a contract
* Steps before entering a contract
* Legitimate interests in administering business Accounts

### 8.3 Payments and Accounting

We use information to:

* Process payments
* Issue invoices
* Manage refunds
* Maintain financial records
* Prevent fraud
* Recover unpaid amounts
* Meet tax and company-law requirements

Lawful bases:

* Performance of a contract
* Legal obligations
* Legitimate interests in maintaining accurate records

### 8.4 Service Delivery and Support

We use information to:

* Activate Devices
* Configure authorised settings
* Diagnose faults
* Answer support requests
* Maintain compatibility
* Investigate connection problems
* Assist with authorised footage retrieval

Lawful bases:

* Performance of a contract
* Legitimate interests in providing support
* Legal obligations where applicable

When processing Customer Content solely for a Customer, we act on that Customer’s instructions.

### 8.5 Security and Misuse Prevention

We use information to:

* Authenticate users
* Prevent unauthorised access
* Investigate suspected spying
* Detect fraud
* Prevent cyberattacks
* Enforce our Terms
* Protect individuals
* Preserve relevant evidence
* Secure the platform

Lawful bases:

* Legitimate interests
* Legal obligations
* Legal claims
* Vital interests in exceptional circumstances

### 8.6 Service Communications

We may send communications about:

* Activation
* Password resets
* Security
* Maintenance
* Subscription expiry
* Invoices
* Support
* Legal changes
* Privacy information

Lawful bases:

* Performance of a contract
* Legal obligations
* Legitimate interests

Essential service communications cannot always be opted out of while an Account is active.

### 8.7 Marketing

We may send information about:

* CMSV6 hosting
* Compatible iCustodian products
* New functions
* Offers
* Renewals
* Related services

Lawful bases may include:

* Consent
* Legitimate interests where permitted
* Applicable electronic-marketing rules

You may unsubscribe at any time.

### 8.8 Analytics and Website Improvement

Where required choices have been obtained, we may use analytics to:

* Understand website use
* Identify errors
* Improve navigation
* Measure campaigns
* Improve content

Lawful bases may include:

* Consent
* Legitimate interests where otherwise legally permitted

### 8.9 Legal and Regulatory Purposes

We may process information to:

* Respond to lawful requests
* Comply with court orders
* Meet regulatory requirements
* Handle rights requests
* Investigate complaints
* Defend claims
* Enforce agreements
* Cooperate with authorities where lawful

Lawful bases:

* Legal obligations
* Legitimate interests
* Legal claims
* Vital interests where applicable

---

## 9. Legitimate Interests

Our legitimate interests may include:

* Operating our business
* Responding to enquiries
* Providing customer service
* Maintaining security
* Preventing fraud
* Preventing unlawful surveillance
* Protecting individuals
* Managing customer relationships
* Recovering debts
* Defending claims
* Maintaining business records
* Marketing relevant services where permitted

We consider whether the processing is necessary and whether our interests are overridden by individual rights.

---

## 10. Sensitive Information

We do not normally request sensitive information when creating an ordinary Account.

Customer Content or support material may incidentally reveal:

* Health information
* Racial or ethnic origin
* Religious beliefs
* Trade union membership
* Biometric information
* Sexual orientation
* Criminal allegations or offences

Where we process such information as a processor, the Customer is responsible for identifying the required lawful basis and additional condition.

Where we act as controller, we will identify an appropriate legal basis and condition before using it unless an emergency or legal exception applies.

We do not use ordinary Customer footage to build biometric databases for our own independent purposes.

---

## 11. How We Use Customer Content

We process Customer Content only where reasonably necessary to:

* Deliver live video
* Deliver audio where enabled
* Display GPS locations
* Display historical routes
* Show Device status
* Retrieve requested footage
* Generate requested snapshots
* Provide events or reports
* Maintain security
* Diagnose technical problems
* Follow lawful instructions
* Meet legal obligations

We do not use Customer Content to:

* Advertise to recorded individuals
* Sell information to data brokers
* Monitor Customers for unrelated purposes
* Create public databases
* Track people independently
* Train unrelated commercial AI systems
* Publicly display private footage
* Conduct covert surveillance on our own behalf

Limited access may occur where:

* The Customer requests support.
* Access is required to diagnose a problem.
* There is a suspected security incident.
* Credible unlawful use is being investigated.
* Access is legally required.
* Access is necessary to protect someone from serious harm.

Access will be limited to authorised personnel and what is reasonably necessary.

---

## 12. Customer Responsibilities

Customers using CMSV6 are responsible for their surveillance and tracking activities.

Responsibilities may include:

* Selecting a lawful basis
* Completing an impact assessment
* Displaying CCTV signs
* Providing privacy notices
* Informing drivers and employees
* Consulting workers
* Managing consent where relied upon
* Restricting audio
* Controlling access
* Setting retention periods
* Responding to access requests
* Securing local footage
* Avoiding unnecessary camera coverage
* Protecting children and vulnerable people
* Meeting licensing requirements
* Registering with an appropriate regulator
* Paying any applicable data-protection fee

Our supply of CMSV6 does not make a Customer’s intended monitoring automatically lawful.

---

## 13. Sharing Personal Information

### 13.1 Service Providers

We may use providers of:

* UK server infrastructure
* Website hosting
* Platform software
* Email delivery
* Customer support
* Cybersecurity
* Backup services
* Analytics
* Error monitoring
* Payment processing
* Accounting
* Delivery

Providers may process information only for agreed purposes under appropriate contractual and security requirements.

### 13.2 Technical Platform Providers

Specialist software or engineering providers may help operate and support CMSV6.

Access will be restricted according to role and necessity.

Providers processing Customer Content on our behalf will normally act as sub-processors.

### 13.3 Professional Advisers

We may share information with:

* Solicitors
* Accountants
* Auditors
* Insurers
* Security consultants
* Data-protection advisers

### 13.4 Authorities and Courts

We may disclose information where:

* Required by law
* Required by a valid court order
* Requested through lawful regulatory processes
* Necessary to investigate crime
* Necessary to prevent serious harm
* Necessary for legal claims

We will assess requests and disclose only information we reasonably believe is lawful and appropriate.

### 13.5 Business Transfers

Information may be shared during a merger, sale, restructuring, investment or transfer of business.

Appropriate confidentiality and data-protection measures will be used where applicable.

### 13.6 Customer-Directed Disclosures

Customers may choose to:

* Download footage
* Share snapshots
* Export reports
* Add Authorised Users
* Disclose information to insurers
* Disclose information to authorities
* Disclose information to employers or other parties

These decisions are controlled by the Customer.

---

## 14. We Do Not Sell Personal Information

We do not sell personal information or Customer Content to:

* Data brokers
* Advertisers
* Unrelated third parties

We do not exchange Customer footage for advertising benefits.

We do not use private footage publicly without appropriate permission and lawful authority.

---

## 15. UK Hosting and International Access

The core CMSV6 server environment supplied through cmsv6.co.uk is hosted in the United Kingdom.

We provide services to Customers in other countries.

As a result:

* Overseas Customers may access UK-hosted information.
* Customers may appoint users in multiple countries.
* Footage may be viewed or downloaded overseas.
* Ancillary technology providers may operate internationally.
* Approved overseas technical providers may occasionally assist with support.

Where we make a restricted international transfer, we will use an appropriate mechanism where required, such as:

* UK adequacy regulations
* A UK International Data Transfer Agreement
* An approved UK contractual addendum
* Another legally recognised safeguard
* A lawful exception

Customers are responsible for international transfers created by their own:

* Authorised Users
* Overseas branches
* Contractors
* Downloads
* Disclosure instructions

---

## 16. Retention

We retain information only for as long as reasonably necessary.

### Enquiries

General enquiries that do not become contracts will normally be kept for up to **24 months after the last meaningful contact**.

### Active Accounts

Account information will be kept while the Account remains active.

Core contractual records may be retained for up to **six years after the relationship ends**.

### Financial Records

Invoices, transactions and accounting information will normally be retained for up to **six years** or longer where legally required.

### Device Records

Device activation and configuration records will normally be retained during the active service and for up to **24 months after deactivation**.

They may be retained longer for security, fraud prevention, warranties, disputes or legal claims.

### Support Records

Routine support records will normally be kept for up to **three years after a case closes**.

They may be retained longer where connected with disputes, security incidents, misuse or legal claims.

### Website and Security Logs

Routine logs will generally be retained for up to **12 months**.

Relevant logs may be retained longer to investigate security incidents, fraud, unlawful surveillance or legal matters.

### Marketing Information

Marketing information will be kept until:

* You unsubscribe
* You object
* Consent is withdrawn
* The information is no longer accurate
* Continued marketing is no longer appropriate

A minimal suppression record may be retained to respect an opt-out.

### Live Streams

Live video and audio are intended for real-time delivery and are not routinely retained by us as permanent recordings unless a storage function is configured.

Short-lived buffers or caches may be created automatically and overwritten when no longer technically required.

### Server-Stored Clips and Events

Retention of snapshots, clips, alarm media and downloaded files depends on:

* The service purchased
* Customer configuration
* Device settings
* Available storage
* Customer instructions
* Applicable law

CMSV6 must not be treated as a permanent archive unless a specific storage arrangement has been agreed.

### Account Closure

After closure:

* Remote access may be disabled.
* Device reporting may stop.
* Customer Content may be scheduled for deletion.
* Required technical and legal records may be retained.
* Deleted information may remain temporarily in secure backups.

Backups are isolated from ordinary use and overwritten according to applicable backup cycles.

### Complaints and Claims

Complaint and legal-claim records may be retained for up to **six years after resolution**, or longer where proceedings continue.

---

## 17. Security

We use reasonable technical and organisational measures, which may include:

* Access controls
* User permissions
* Authentication
* Protected communications where supported
* Secure server environments
* Network protection
* Activity logging
* Restricted administrative access
* Confidentiality obligations
* Security monitoring
* Backup controls
* Incident procedures
* Supplier checks
* Data minimisation

Customers must also:

* Change default passwords.
* Use strong credentials.
* Protect administrator Accounts.
* Remove former users.
* Secure computers and phones.
* Update supported firmware.
* Secure local DVR storage.
* Protect SIM cards and routers.
* Restrict access to footage.
* Report suspected compromise.

No internet-connected service can be completely secure.

Sensitive footage should not be sent through ordinary unencrypted email.

---

## 18. Personal Data Breaches

Where a breach affects information for which we are controller, we will:

* Investigate
* Contain the incident
* Assess risk
* Document the incident
* Notify the regulator where required
* Inform affected individuals where required

Where we act as processor, we will notify the relevant Customer without undue delay after becoming aware of a qualifying breach.

Customers must report suspected unauthorised access promptly to [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk).

---

## 19. Your Rights

Depending on the circumstances, you may have rights to:

* Be informed about processing
* Access your personal information
* Correct inaccurate information
* Request deletion
* Restrict processing
* Receive portable information
* Object to legitimate-interest processing
* Object to direct marketing
* Withdraw consent
* Challenge certain automated decisions

These rights are not always absolute.

We may retain information where required for:

* Legal obligations
* Contract records
* Security
* Fraud prevention
* Legal claims
* Another lawful reason

You have an absolute right to object to direct marketing.

---

## 20. Automated Alerts and Decisions

CMSV6 may generate automated technical alerts, including:

* Device-status alerts
* Camera-loss alerts
* Geofence events
* Speed events
* Driver-safety alerts

iCustodian does not normally use these alerts to make solely automated decisions producing legal or similarly significant effects.

Customers should apply appropriate human review before taking important disciplinary, insurance, employment or legal action.

---

## 21. Requests About Customer Footage

Where you appear in footage controlled by a CMSV6 Customer, that Customer will normally be responsible for your request.

The controller may be:

* A taxi operator
* A fleet company
* An employer
* A shop
* A school
* A care provider
* A homeowner
* A farm
* A transport provider
* A public authority

You should normally contact the organisation identified on its:

* CCTV signs
* Vehicle notices
* Privacy notice
* Website
* Relevant correspondence

If you contact iCustodian:

* We may ask for information to identify the relevant Customer.
* We may forward the request to the Customer.
* We may assist the Customer as processor.
* We will not normally disclose footage without the controller’s authority or another legal basis.
* We may be unable to retrieve footage held only on a local DVR.

---

## 22. Exercising Your Rights

Contact:

**Email:** [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)
**Subject:** Data Protection Request

Please provide:

* Your name
* Contact details
* Relationship with iCustodian
* Account or order number where applicable
* The right being exercised
* A description of the information
* Relevant dates or locations

We may request reasonable evidence of identity or authority.

We will not request more identification than necessary.

We will respond within the period required by applicable law.

---

## 23. Data-Protection Complaints

You may complain if you believe that your personal information has not been handled properly.

Contact:

**Email:** [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)
**Subject:** Data Protection Complaint

Please provide:

* Your name
* Contact details
* Description of the concern
* Relevant dates
* Account, order or Device information
* Relevant correspondence
* The outcome requested

We will:

* Provide a clear complaint route
* Acknowledge the complaint within the legally required period
* Investigate without undue delay
* Keep you reasonably informed
* Communicate the outcome

You may also complain to:

**Information Commissioner’s Office**
Wycliffe House
Water Lane
Wilmslow
Cheshire
SK9 5AF
United Kingdom

You may also have the right to contact a regulator in your country.

---

## 24. Cookies

Our website may use cookies or similar technologies for:

* Website operation
* Security
* Login sessions
* Preferences
* Cookie choices
* Analytics
* Performance
* Marketing measurement

Strictly necessary technologies may operate without optional consent where legally permitted.

Non-essential cookies will not intentionally be activated before the required user choice has been obtained.

Further details will be provided in our Cookie Policy and consent interface.

---

## 25. Marketing

We may send marketing where:

* You have consented
* You requested information
* You are an existing Customer and the communication concerns related services where legally permitted
* Another lawful basis applies

Messages will identify iCustodian and provide an opt-out method.

You may unsubscribe through:

* An unsubscribe link
* Account preferences where available
* [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)

Opting out of marketing does not stop essential messages concerning:

* Security
* Billing
* Accounts
* Expiry
* Support
* Legal notices

---

## 26. Children

CMSV6 Accounts are intended for adults and organisations.

A person must normally be at least 18 to purchase hosting or administer an Account.

Customer cameras may capture children in:

* School transport
* Nurseries
* Schools
* Family vehicles
* Homes
* Shops
* Public areas
* Healthcare environments

The relevant Customer is responsible for:

* Safeguarding
* Appropriate notices
* Lawful camera placement
* Restricted access
* Retention
* Children’s rights
* Higher protection requirements

CMSV6 must not be used to record children in toilets, changing facilities or other inappropriate private settings.

---

## 27. AI-Assisted Functions

Compatible Devices may provide:

* Driver-status monitoring
* ADAS alerts
* Object detection
* Pedestrian detection
* Blind-spot detection
* Passenger counting
* Facial detection
* Vehicle analytics

These functions may produce inaccurate or delayed results.

Customers must:

* Assess legality and necessity
* Provide transparency
* Complete an impact assessment where required
* Apply meaningful human review
* Avoid treating alerts as infallible
* Avoid relying solely on inaccurate alerts for important decisions

We will provide additional information if we introduce significant automated decision-making for which iCustodian is the controller.

---

## 28. Third-Party Websites

Our services may link to:

* iCustodian product pages
* Payment providers
* App stores
* Mapping providers
* Manufacturers
* Technical documentation

Independent third parties have their own privacy policies.

We are not responsible for their independent privacy practices.

---

## 29. Changes to This Policy

We may update this Privacy Policy to reflect:

* Service changes
* New functions
* New providers
* Security improvements
* Business changes
* Legal changes
* Regulatory guidance
* Clarifications

The latest version will be published on cmsv6.co.uk with its revision date.

Material changes may also be communicated through the website, Account or email.

---

## 30. Contact Us

For privacy questions, rights requests, security reports or complaints:

**iCustodian Limited**
Trading as **iCustodian®**

**Company number:** 15930836
**Registered office:** 18 Holly Hill Road, Erith, England, DA8 1QD, United Kingdom
**ICO registration:** iCustodian Limited is registered with the Information Commissioner’s Office
**Email:** [support@cmsv6.co.uk](mailto:support@cmsv6.co.uk)
**Website:** cmsv6.co.uk`,
} as const;

