export type ContentSection = {
  heading: string;
  paragraphs: readonly string[];
  bullets?: readonly string[];
};

export type SeoContentPage = {
  section: "solutions" | "resources";
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  h1: string;
  intro: string;
  definition: string;
  takeaways: readonly string[];
  sections: readonly ContentSection[];
  faqs: readonly (readonly [string, string])[];
  related: readonly (readonly [string, string])[];
  published: string;
  reviewed: string;
};

const published = "2026-08-02";

export const solutionPages: readonly SeoContentPage[] = [
  {
    section: "solutions", slug: "vehicle-cctv",
    title: "Vehicle CCTV Live Streaming & GPS | CMSV6 UK",
    description: "Connect compatible multi-camera vehicle CCTV to CMSV6 for live viewing, local recording, remote playback and GPS reporting from cars, vans and specialist vehicles.",
    eyebrow: "Vehicle CCTV", h1: "Vehicle CCTV with live remote viewing and GPS",
    intro: "CMSV6 gives authorised users remote access to compatible vehicle cameras while the DVR continues recording locally. It can support private cars, vans, plant, public-service vehicles and other lawful mobile installations.",
    definition: "Vehicle CCTV with CMSV6 combines a compatible mobile DVR, fitted cameras, local storage and a suitable internet connection so authorised users can view live video, request supported playback and see GPS information where fitted.",
    takeaways: ["Local DVR recording remains the primary evidence store unless separate server storage is configured.", "Live video and GPS depend on mobile coverage, data allowance, antennas and compatible hardware.", "Road, cabin, side, rear and load-area cameras should be selected around the vehicle and lawful purpose."],
    sections: [
      { heading:"What a connected vehicle system can show", paragraphs:["A well-planned installation can provide a forward road view, passenger or driver-area coverage where lawful, side and rear visibility, and a protected view of a load or working area. CMSV6 brings supported channels into one remote interface rather than changing how the DVR records locally."], bullets:["Live multi-camera checks while the vehicle is connected", "Remote playback or clip retrieval where the DVR and account support it", "Current location, direction and journey information from GPS-enabled units", "Camera-loss, power, SOS or other configured device events"] },
      { heading:"Plan cameras around the actual risk", paragraphs:["A private car may need only a forward and cabin view. A van may benefit from road, rear-door and load-area cameras. Specialist vehicles can require side views, reversing coverage or additional sensors. Camera placement must preserve useful detail without capturing more people or private space than necessary.","Night performance, vibration resistance, weather protection, cable routing, storage capacity and tamper protection matter as much as channel count."], bullets:["Front road camera for incident context", "Rear or reversing view for manoeuvring and evidence", "Side cameras for blind areas on larger vehicles", "Interior coverage only where justified, transparent and lawful"] },
      { heading:"Connectivity and offline behaviour", paragraphs:["A mobile system normally uses a data SIM and suitable antennas. Video quality, frame rate, channel count and viewing time all affect data use. When connectivity drops, a correctly configured DVR normally continues recording to local media; remote live view and GPS updates resume when the connection returns.","CMSV6 is not an emergency-response service and does not guarantee uninterrupted tracking, theft recovery or the prevention of an incident."] },
      { heading:"Responsible use", paragraphs:["Vehicle operators should document why cameras, audio and location data are needed, tell affected drivers and passengers, restrict user permissions and set suitable retention rules. Audio is often more intrusive than video and should not be enabled by default. Private use of company vehicles needs particular care."] }
    ],
    faqs:[["Can CMSV6 work with an existing vehicle DVR?","Possibly. Manufacturer, model, firmware, channel configuration and remote protocol must be checked before compatibility is confirmed."],["Does the vehicle stop recording when mobile data fails?","A compatible DVR normally keeps recording locally if it still has power and healthy storage. Live access and GPS reporting pause until connectivity returns."],["Is a SIM card included with hosting?","No. The SIM, mobile-data plan, antennas and connectivity are separate unless a quotation expressly includes them."],["Can several people view the same vehicle?","Separate authorised users may be configured where supported. Access should be limited to people with a legitimate operational need."]],
    related:[["Fleet CCTV and video telematics","/solutions/fleet-cctv-and-video-telematics"],["Choosing a compatible DVR","/resources/choosing-a-cmsv6-compatible-dvr"],["CMSV6 hosting prices","/pricing"]], published, reviewed:published
  },
  {
    section:"solutions", slug:"fleet-cctv-and-video-telematics",
    title:"Fleet CCTV Live Video & GPS Tracking | CMSV6 UK",
    description:"Combine compatible fleet CCTV, live multi-camera video, remote playback and GPS reporting through UK-hosted CMSV6. Request a multi-vehicle quotation.",
    eyebrow:"Fleet video telematics", h1:"Fleet CCTV live video, remote playback and GPS",
    intro:"CMSV6 can organise compatible multi-camera vehicle DVRs across fleets, depots and branches, giving authorised teams a practical view of video, device status and GPS information without treating every vehicle as a separate system.",
    definition:"Fleet video telematics connects vehicle video and location information so an authorised team can investigate incidents, check equipment status and understand journeys using compatible mobile DVRs and cameras.",
    takeaways:["Use live viewing for proportionate operational checks, not continuous employee observation.","Keep high-quality evidence on protected local DVR storage and retrieve only what is needed.","Structure accounts, permissions and vehicle groups around real responsibilities."],
    sections:[
      {heading:"A clearer view across several vehicles",paragraphs:["A fleet account can group compatible vehicles by depot, branch, contract or operating team. Road, side, rear, cabin and cargo cameras can be presented consistently, while GPS-enabled units add current position and journey context.","The strongest use case is fast, authorised investigation: confirm that a vehicle is online, review the relevant channel, identify the time window and retrieve supported footage without waiting for the vehicle to return."],bullets:["Multi-vehicle maps and status views where supported","Road, side, rear and cargo channels","Remote incident review and evidence retrieval","Camera-loss, power and configured safety events","Role-based access for fleet, safety and investigation teams"]},
      {heading:"From alert to human review",paragraphs:["Compatible equipment may provide ADAS, driver-monitoring, blind-spot or sensor events. These signals should direct trained people to review context; they are not infallible findings and should not be used as the sole basis for disciplinary or safety decisions.","Define who receives events, which footage may be viewed, how conclusions are recorded and when access is removed." ]},
      {heading:"Deployment decisions that affect results",paragraphs:["Channel count, camera field of view, frame rate, storage size, SIM coverage and data policy should be designed together. An eight-channel lorry produces very different storage and connectivity demands from a four-channel van.","Pilot a representative vehicle before a wider rollout. Confirm day and night image quality, GPS reception, offline recording, remote playback and the installation’s electrical behaviour."],bullets:["Name devices and channels consistently","Document storage and retention settings","Use protected, encrypted storage where appropriate","Review user access after role changes","Budget mobile data around actual viewing policy"]},
      {heading:"Lawful and proportionate fleet use",paragraphs:["Drivers and other affected people should receive clear information about video, audio, location and automated events. Monitoring should be necessary for a defined purpose, limited to relevant users and reviewed regularly. CMSV6 does not replace workforce consultation, a data-protection impact assessment where required, or specialist legal advice."]}
    ],
    faqs:[["Can CMSV6 show every fleet vehicle on one account?","Compatible devices can be organised in one account or structured groups where the configured platform permissions support it."],["Can a fleet manager download footage remotely?","Authorised retrieval may be available from compatible DVR storage or configured server storage. Connection quality and device settings affect speed and availability."],["Does CMSV6 include driver scoring?","CMSV6 hosting does not make every AI or telematics feature standard. Any scoring, ADAS or driver-monitoring function depends on verified compatible equipment and configuration."],["How is fleet pricing calculated?","Published prices are per compatible device. Multi-device, longer-term and specialist requirements can be quoted separately."]],
    related:[["Vehicle CCTV","/solutions/vehicle-cctv"],["Lorry and HGV CCTV","/solutions/lorry-hgv-cctv"],["Request a fleet quotation","/contact?enquiry=fleet"]],published,reviewed:published
  },
  {
    section:"solutions", slug:"taxi-private-hire-cctv",
    title:"Taxi & Private-Hire CCTV with GPS | CMSV6 Remote Viewing",
    description:"Plan compatible taxi and private-hire CCTV with protected local recording, remote incident review and GPS through CMSV6, subject to local licensing and privacy rules.",
    eyebrow:"Taxi and private hire", h1:"Taxi CCTV with protected recording and remote access",
    intro:"CMSV6 can connect compatible taxi and private-hire DVRs for authorised live checks, incident review and GPS context. Camera, audio, signage and retention requirements vary between licensing authorities and must be verified locally.",
    definition:"A taxi CCTV system uses fitted road-facing and, where lawful, interior cameras connected to protected DVR storage; CMSV6 adds supported remote access and GPS functions without replacing local licensing requirements.",
    takeaways:["Never claim a system is council, TfL or licensing approved without documentary evidence for that exact installation.","Interior video and audio require careful necessity, signage, access and retention decisions.","Encrypted or key-protected storage helps reduce unauthorised access to recordings."],
    sections:[
      {heading:"Useful camera positions",paragraphs:["A road-facing camera can record traffic context. A driver-facing or passenger-area camera may support incident and complaint investigation where it is lawful, necessary and clearly disclosed. Additional rear or exterior views may help with collisions and manoeuvring.","The purpose of each camera should be documented. Avoid unnecessary capture of screens, private conversations or areas outside the vehicle."],bullets:["Forward road view","Driver and passenger area only where authorised","Rear or exterior context where justified","Clear signage and accessible privacy information"]},
      {heading:"Incident review without weakening evidence security",paragraphs:["Compatible systems can keep recordings on encrypted or physically protected local media. Remote access may allow an authorised person to find the relevant time and channel before the vehicle returns, subject to connection and device support.","Access logs, named users and a documented disclosure process help protect drivers, passengers and evidence integrity." ]},
      {heading:"GPS, private use and audio",paragraphs:["GPS history can add journey context, but operators should distinguish licensed work from private use and restrict location access accordingly. Audio recording is more intrusive than video and should only be enabled after confirming a lawful, necessary purpose and applicable licensing conditions.","CMSV6 does not guarantee that a live feed will be continuously available and is not a staffed emergency service." ]},
      {heading:"Check local requirements before installation",paragraphs:["Taxi and private-hire licensing conditions differ. Confirm the authority’s current rules for approved installers, signage, encryption, access, retention, audio and data-controller responsibilities before selecting equipment or changing settings."]}
    ],
    faqs:[["Is CMSV6 approved by my licensing authority?","No general approval is claimed. Check the rules and any approved-equipment list for the specific licensing authority before installation."],["Can passengers be recorded?","Interior recording may be permitted only under specific lawful, licensing and transparency conditions. Obtain appropriate advice and display the required notices."],["Can audio be turned on?","Only where the exact use is lawful, necessary and supported. Audio should not be enabled by default."],["Can footage be viewed while the taxi is moving?","Technically supported live viewing may be available to authorised remote users, but it must be used proportionately and never distract the driver."]],
    related:[["Responsible CCTV use","/responsible-use"],["Vehicle CCTV","/solutions/vehicle-cctv"],["Check device compatibility","/cmsv6-device-compatibility"]],published,reviewed:published
  },
  {
    section:"solutions",slug:"lorry-hgv-cctv",
    title:"Lorry & HGV CCTV Live View | CMSV6 Video Telematics",
    description:"Connect compatible lorry and HGV multi-camera CCTV to CMSV6 for live viewing, local evidence, remote playback, GPS and supported safety events.",
    eyebrow:"Lorry and HGV CCTV",h1:"Multi-camera lorry CCTV with remote visibility",
    intro:"Large vehicles have substantial blind areas and complex evidence needs. CMSV6 can connect compatible four- or eight-channel mobile DVRs so authorised teams can review road, side, rear, cab and load views alongside GPS context.",
    definition:"Lorry and HGV CCTV combines rugged multi-camera hardware, protected local DVR recording and optional remote video and GPS access for incident investigation and operational checks.",
    takeaways:["Camera positions should be validated on the actual vehicle body and trailer combination.","Side and rear coverage can add context but does not replace mirrors, direct vision or safe driving procedures.","AI and blind-spot events require compatible sensors, configuration and human review."],
    sections:[
      {heading:"Typical HGV camera layout",paragraphs:["A practical design may include forward road, nearside, offside and rear cameras, with further channels for the cab, load, coupling area or specialist body. Articulated and rigid vehicles need different cable, trailer and field-of-view planning.","Treat any diagram as a starting point. Verify blind areas, mounting height, infrared reflection, weather exposure and night image quality on the real vehicle."],bullets:["Forward road context","Nearside and offside coverage","Rear or reversing view","Cab or load view where justified","Optional trailer or specialist-equipment channels"]},
      {heading:"Remote incident handling",paragraphs:["When a collision, allegation or load event is reported, an authorised team may be able to locate the vehicle, identify relevant channels and retrieve supported footage before overwrite. Local storage remains essential when mobile data is weak or the vehicle is offline.","Preserve original evidence, record who accessed it and avoid repeated downloads that create uncontrolled copies." ]},
      {heading:"Data, storage and reliability",paragraphs:["More channels and higher image quality increase both storage and live-view data use. Select disk or SD capacity around the required retention window, operating hours and recording mode. Use suitable antennas and a realistic multi-network or roaming strategy where coverage is critical.","CMSV6 cannot guarantee continuous connectivity, exact GPS accuracy or the prevention of collisions or theft." ]},
      {heading:"Driver and workforce transparency",paragraphs:["Explain which cameras, microphones, GPS and safety sensors are active, who can view them and why. Limit live viewing to justified circumstances and ensure automated events are reviewed in context before decisions are made."]}
    ],
    faqs:[["Do I need an eight-channel DVR for an HGV?","Not always. Channel count depends on the vehicle, trailer, required views and future expansion. A compatibility and camera-planning review is recommended."],["Can CMSV6 show blind-spot alerts?","Only when compatible cameras, sensors, licences and device configuration support those events."],["Will footage remain if the vehicle loses signal?","A correctly configured DVR normally records locally while it has power and healthy storage; remote access returns with connectivity."],["Can the same system support several depots?","Compatible devices can be grouped and permissions structured around depots or teams where supported."]],
    related:[["Fleet CCTV and video telematics","/solutions/fleet-cctv-and-video-telematics"],["Compatible iCustodian DVRs","/equipment"],["Live video versus playback","/resources/live-cctv-versus-recorded-playback"]],published,reviewed:published
  },
  {
    section:"solutions",slug:"business-cctv",
    title:"Business CCTV Remote Viewing | Shops, Offices & Warehouses",
    description:"Use compatible CMSV6-connected CCTV for authorised remote viewing across shops, offices, warehouses, factories, depots and multiple business sites.",
    eyebrow:"Business premises",h1:"Business CCTV remote viewing across one or several sites",
    intro:"CMSV6 is not limited to vehicles. Compatible fixed-site DVRs can provide authorised live viewing and supported playback for shops, offices, warehouses, factories, depots and temporary business locations.",
    definition:"Business CCTV remote viewing lets authorised users connect to compatible cameras and DVR recordings over the internet without turning the service into a staffed monitoring centre.",
    takeaways:["CMSV6 provides customer remote access; iCustodian staff do not continuously watch customer cameras.","Use separate user permissions for sites, branches and investigation roles.","Employee monitoring must be transparent, necessary and proportionate."],
    sections:[
      {heading:"Where remote access can help",paragraphs:["A shop owner may check an entrance or closing procedure. A warehouse manager may review a loading-bay incident. A multi-site operator may confirm which branch is online before requesting playback. These are targeted operational uses rather than continuous surveillance."],bullets:["Entrances, tills and public areas where lawful","Loading bays, yards and car parks","Stock rooms and restricted zones","Factories, depots and temporary sites","Branch and multi-site camera groups"]},
      {heading:"Local recording with remote access",paragraphs:["The DVR records to installed local storage according to its schedule, image quality and retention settings. CMSV6 provides supported remote live view, status and playback while the site has suitable connectivity. Standard hosting does not automatically include permanent cloud-video storage.","A fixed site may use wired broadband, managed Wi-Fi or compatible mobile data. Configure resilient power, secure networking and strong account credentials." ]},
      {heading:"Permissions and evidence handling",paragraphs:["Give users only the sites and functions they need. Separate day-to-day live checks from formal investigation and export permissions where possible. Document retention, disclosure and deletion arrangements, and remove access promptly when roles change."],bullets:["Named accounts rather than shared credentials","Multi-factor protection where supported","Regular permission review","Controlled downloads and evidence copies","Clear incident and subject-access procedures"]},
      {heading:"Workplace privacy",paragraphs:["Tell employees and visitors what is monitored and why. Avoid private areas, excessive audio and monitoring that is unrelated to a defined purpose. Consider a data-protection impact assessment for higher-risk monitoring and obtain professional advice where appropriate."]}
    ],
    faqs:[["Is CMSV6 a staffed alarm-monitoring centre?","No. CMSV6 provides remote access for authorised customer users and does not mean iCustodian staff continuously monitor cameras."],["Can several branches use one account?","Compatible devices may be grouped by site with suitable permissions, subject to the account configuration."],["Does hosting include cloud recording?","No permanent cloud-video storage is included automatically. Local DVR storage is separate, and any server storage must be expressly configured."],["Can CMSV6 use an existing business DVR?","Possibly. Send the manufacturer, model, firmware, channel count and connection details for manual verification."]],
    related:[["Warehouse and factory CCTV overview","/solutions"],["Responsible CCTV use","/responsible-use"],["CMSV6-compatible DVRs","/equipment"]],published,reviewed:published
  },
  {
    section:"solutions",slug:"farm-cctv",
    title:"Farm CCTV with Remote Viewing | CMSV6 Livestock Monitoring",
    description:"Monitor compatible barn, livestock, machinery, entrance and remote farm cameras through CMSV6, with local DVR recording and remote viewing over suitable 4G or Wi-Fi.",
    eyebrow:"Farm and rural CCTV",h1:"Farm CCTV for remote barns, livestock and rural assets",
    intro:"CMSV6 can connect compatible cameras around barns, livestock buildings, gates, stores and machinery areas, helping authorised users check conditions remotely while retaining local DVR recording.",
    definition:"Remote farm CCTV combines weather-suitable cameras, a compatible DVR, local storage and available 4G, Wi-Fi or wired connectivity so selected farm areas can be viewed without every check requiring a journey.",
    takeaways:["Remote viewing can reduce unnecessary journeys but never replaces direct animal-welfare checks.","Survey signal, power, night lighting and camera protection at each building before installation.","Keep cameras away from neighbouring private areas and use clear signage where people may be recorded."],
    sections:[
      {heading:"Practical farm locations",paragraphs:["Useful locations may include cattle sheds, lambing and calving areas, stables, poultry buildings, machinery sheds, fuel and feed stores, gates, yards and remote entrances. The purpose determines lens, mounting height, night performance and whether live detail or general overview is needed."],bullets:["Barn and livestock overview","Calving or lambing observation as a supporting tool","Machinery, fuel and feed stores","Gates, yards and farm entrances","Remote outbuildings and field-edge assets"]},
      {heading:"Connectivity across rural buildings",paragraphs:["Broadband may reach the farmhouse but not a remote shed. A design can use point-to-point Wi-Fi, wired links or mobile data where supported. Test the real signal inside the intended DVR location and with doors closed; rural construction and terrain can materially change performance.","If connectivity fails, a powered compatible DVR should continue local recording. Live video, GPS and remote requests return when the connection does." ]},
      {heading:"Night viewing and equipment protection",paragraphs:["Dust, moisture, cobwebs, insects, vibration and condensation can degrade an otherwise good picture. Select appropriate camera housings, protect cables and clean lenses as part of routine maintenance. Infrared lighting must be tested for reflections from walls, roofs and nearby surfaces."],bullets:["Confirm identification needs rather than relying only on wide views","Protect DVR and storage from unauthorised access","Use suitable surge and power protection","Review image quality through changing seasons"]},
      {heading:"Animal welfare and privacy",paragraphs:["Cameras can help an owner decide when to travel or where to look first, but they cannot assess every welfare condition and should not replace required physical inspection. Where staff, contractors or visitors are captured, provide clear information and restrict access to a defined purpose."]}
    ],
    faqs:[["Can CMSV6 work on a farm without fixed broadband?","It may work through compatible mobile data or another supported network, but signal and bandwidth must be tested at the equipment location."],["Can I use a camera for calving or lambing?","A suitable camera can support remote observation, but it is not a substitute for direct welfare checks or veterinary advice."],["What happens during an internet outage?","Local recording normally continues on a compatible powered DVR; remote functions pause until connectivity returns."],["Can several barns appear in one account?","Compatible DVRs at separate buildings can be organised together where the account and connectivity are configured accordingly."]],
    related:[["CMSV6 GPS tracking guide","/resources/cmsv6-gps-tracking-guide"],["Check rural equipment compatibility","/cmsv6-device-compatibility"],["Hosting prices","/pricing"]],published,reviewed:published
  },
  {
    section:"solutions",slug:"boat-marine-cctv",
    title:"Boat CCTV & GPS Remote Monitoring | CMSV6 Marine Systems",
    description:"Connect compatible boat and marine CCTV to CMSV6 for authorised live viewing, local recording and GPS information where suitable power and connectivity are available.",
    eyebrow:"Boat and marine CCTV",h1:"Boat CCTV and GPS remote monitoring with CMSV6",
    intro:"CMSV6 can support compatible cameras and DVRs on boats, fishing vessels, yachts, harbour craft and marine storage areas, subject to suitable power, corrosion-resistant installation and available connectivity.",
    definition:"Marine remote CCTV uses appropriately installed cameras and a compatible DVR to record locally while CMSV6 provides supported live, playback and GPS access over a suitable onboard connection.",
    takeaways:["Marine installation requires appropriate housings, connectors, cable protection and power design.","Offshore or harbour connectivity may be intermittent; local recording remains essential.","GPS and camera access support awareness but do not replace navigation, alarms or required safety systems."],
    sections:[
      {heading:"Views worth planning",paragraphs:["Depending on the vessel, cameras may cover the helm, deck, engine access, stern, mooring area or protected storage. The field of view must remain useful in glare, spray, darkness and vessel movement.","Only capture crew, passengers or neighbouring vessels where justified and lawful. Interior audio and private accommodation need particularly careful treatment."],bullets:["Deck and working-area overview","Stern, mooring and access points","Engine or equipment spaces where safe","Helm or navigation context where justified","Shore-side storage or berth coverage"]},
      {heading:"Power, storage and connection",paragraphs:["Choose a DVR and power arrangement suited to the vessel’s electrical system and operating pattern. Protect connectors against corrosion and vibration, provide adequate local storage and confirm antenna positions away from interference.","Harbour Wi-Fi, mobile data and offshore coverage can vary substantially. CMSV6 cannot guarantee continuous live access or precise location reporting in every operating area." ]},
      {heading:"Remote checks and evidence",paragraphs:["Authorised users may use live video for a targeted check while a vessel is connected, or locate and retrieve supported footage after an incident. Recording quality and retention should be set around the most important risks rather than assuming remote access makes every clip permanently available." ]},
      {heading:"Not a marine safety system",paragraphs:["CMSV6 is not a navigation aid, distress service, bilge alarm, vessel-tracking guarantee or substitute for statutory equipment. Optional sensor inputs require confirmed compatible hardware and must be treated as supporting information."]}
    ],
    faqs:[["Will CMSV6 work offshore?","Only where the connected equipment has a suitable supported internet connection. Coverage and bandwidth can be limited away from shore."],["Does a boat DVR record without a signal?","A powered compatible DVR normally records to local storage even when remote connectivity is unavailable."],["Can CMSV6 replace a marine tracker or alarm?","No. It is a remote CCTV and supported GPS platform, not a certified navigation, distress or alarm-response system."],["What cameras are suitable for a boat?","Selection depends on exposure, required detail, night conditions, mounting and the compatible DVR. Request a marine-specific equipment check."]],
    related:[["Vehicle and mobile CCTV principles","/solutions/vehicle-cctv"],["Compatible DVR equipment","/equipment"],["International CMSV6 hosting","/international-cmsv6-hosting"]],published,reviewed:published
  }
] as const;

export const resourcePages: readonly SeoContentPage[] = [
  {
    section:"resources",slug:"what-is-cmsv6",title:"What Is CMSV6? UK Live CCTV, GPS & Remote DVR Guide",description:"A plain-English guide to CMSV6: compatible DVR live viewing, local recording, remote playback, GPS, hosting, connectivity and important limitations.",eyebrow:"CMSV6 explained",h1:"What is CMSV6 and how does it work?",intro:"CMSV6 is a UK-hosted platform that connects compatible CCTV DVRs and mobile DVRs to authorised users for live video, supported audio, GPS information, device status and remote playback.",definition:"iCustodian® CMSV6 is a UK-hosted remote CCTV, live-video, audio and GPS monitoring platform for compatible vehicles, premises, farms, boats and remote locations.",takeaways:["The DVR records locally; CMSV6 provides supported remote access over the internet.","Available features vary by device, firmware, cameras, sensors, permissions and configuration.","Hosting is priced per compatible device and does not automatically include hardware, data or permanent cloud storage."],
    sections:[
      {heading:"The CMSV6 data path",paragraphs:["A camera sends video to a compatible DVR. The DVR records to its installed storage and connects through mobile data, Wi-Fi or a wired network. CMSV6 then provides an authorised remote interface on supported phones, tablets or computers.","If the connection fails, the local recording path can continue while remote live view, GPS updates and requests pause."],bullets:["Camera captures the scene","DVR records to local storage","Internet connection carries supported remote requests","UK-hosted CMSV6 organises authorised access","User views live video, location, status or playback"]},
      {heading:"What CMSV6 can provide",paragraphs:["Depending on the equipment, users may view several camera channels, see GPS-enabled devices, search DVR storage, retrieve clips, receive configured events or use supported voice and control features. A feature shown in CMSV6 is not automatically available on every DVR." ]},
      {heading:"Where CMSV6 can be used",paragraphs:["The same platform can support vehicles and fixed premises. Typical lawful uses include cars, taxis, HGVs, fleets, shops, offices, warehouses, farms, livestock buildings, boats, temporary sites and remote properties." ]},
      {heading:"What hosting does not include",paragraphs:["Standard CMSV6 hosting does not automatically include the DVR, cameras, installation, SIM, mobile data, internet access, local storage media or permanent cloud-video storage. These must be selected or quoted separately." ]}
    ],faqs:[["Is CMSV6 only a fleet tracker?","No. It supports compatible vehicle and fixed-site CCTV, with GPS where the equipment includes it."],["Is CMSV6 monitored by iCustodian staff all day?","No. It provides authorised customer remote access and is not a staffed 24-hour monitoring centre."],["What does hosting cost?","Published per-device terms are £60 for six months, £100 for twelve months and £180 for twenty-four months."],["How do I know whether my DVR works?","Use the compatibility form and provide the exact manufacturer, model, firmware and connection details for manual confirmation."]],related:[["How CMSV6 works","/how-it-works"],["Compatible DVR buying guide","/resources/choosing-a-cmsv6-compatible-dvr"],["Hosting prices","/pricing"]],published,reviewed:published
  },
  {
    section:"resources",slug:"choosing-a-cmsv6-compatible-dvr",title:"CMSV6-Compatible DVR Buying Guide | iCustodian UK",description:"Choose a CMSV6-compatible DVR or MDVR by channel count, storage, connectivity, GPS, camera type, remote playback and installation environment.",eyebrow:"DVR buying guide",h1:"How to choose a CMSV6-compatible DVR",intro:"Compatibility is more than a logo or network socket. The correct DVR must support the required CMSV6 connection, camera channels, storage, firmware and remote functions for the installation.",definition:"A CMSV6-compatible DVR is a verified recorder whose hardware, firmware and connection method can be configured for the CMSV6 service and the functions required by that customer.",takeaways:["Confirm the exact model and firmware before purchase or activation.","Choose four or eight channels around required views and future expansion.","Treat storage, data use, GPS, audio and AI functions as separate design decisions."],
    sections:[
      {heading:"Start with the environment",paragraphs:["A lorry needs vibration resistance, suitable power and mobile antennas. A warehouse may prioritise wired networking and larger local storage. A farm can require weather protection and rural connectivity. A boat adds corrosion, movement and power constraints."],bullets:["Vehicle, fixed building, rural or marine use","Operating temperature and power","Camera connector and video standard","Protected mounting and storage access","Available internet connection"]},
      {heading:"Choose the channel count",paragraphs:["Count the views needed now and likely later. Four channels can suit a car, taxi, van or modest fixed installation. Eight channels may suit an HGV, larger fleet vehicle, warehouse or multi-zone site. A channel should correspond to a useful purpose, not simply be filled." ]},
      {heading:"Storage and remote playback",paragraphs:["Confirm whether the DVR uses SATA disk, SD cards or another medium; the supported capacity; encryption or key protection; and the expected retention at the selected frame rate and recording schedule. Remote playback depends on the DVR, connection and user permissions. It does not turn local storage into permanent cloud storage." ]},
      {heading:"Connectivity, GPS and advanced features",paragraphs:["Check 4G/LTE bands, SIM requirements, Wi-Fi or Ethernet support, antenna connectors and GPS capability. ADAS, driver monitoring, blind-spot and sensor functions require specific compatible components and configuration; do not assume they are included in every CMSV6 device."],bullets:["Exact manufacturer and model","Current firmware","Channel and camera standards","4G, Wi-Fi or wired connection","GPS, audio and remote-playback requirements","Required AI or sensor inputs"]}
    ],faqs:[["Can any DVR connect to CMSV6?","No. Compatibility depends on the exact recorder, firmware and supported remote protocol."],["Is four channels enough?","It depends on the installation. List each required view and allow for justified future expansion before choosing."],["Does a larger hard drive improve live viewing?","No. Storage capacity affects local retention; live viewing depends mainly on the DVR, cameras, connection and settings."],["Where can I buy a verified unit?","The CMSV6 equipment page links to selected compatible iCustodian recorders and the wider DVR range."]],related:[["Compatible equipment","/equipment"],["Manual compatibility checker","/cmsv6-device-compatibility"],["Vehicle CCTV","/solutions/vehicle-cctv"]],published,reviewed:published
  },
  {
    section:"resources",slug:"live-cctv-versus-recorded-playback",title:"Live CCTV Viewing vs Recorded Playback | CMSV6 Guide",description:"Understand the difference between CMSV6 live CCTV viewing, local DVR recording, remote playback and video download, including connectivity and storage limits.",eyebrow:"Live and recorded video",h1:"Live CCTV viewing versus recorded DVR playback",intro:"Live viewing answers what is happening now. Playback answers what the compatible DVR recorded earlier. Both use the connection differently and both depend on correct camera, storage and account configuration.",definition:"Live CCTV streams a current camera feed to an authorised user, while playback searches previously recorded footage on compatible local or separately configured storage.",takeaways:["Live viewing uses data while it is open and depends on current connectivity.","Local recording can continue during an internet outage if the DVR has power and healthy storage.","Remote download creates an additional copy that must be controlled and protected."],
    sections:[
      {heading:"Live viewing",paragraphs:["A live request asks the DVR to send one or more current channels. Image quality, channel count, frame rate and viewing duration affect bandwidth and mobile-data use. Live viewing is useful for targeted checks, but continuous viewing can be intrusive and expensive." ]},
      {heading:"Local recording",paragraphs:["The DVR writes footage to installed storage according to its schedule and settings. Retention depends on storage size, channels, resolution, frame rate, activity and overwrite policy. CMSV6 hosting does not automatically preserve every recording on a server." ]},
      {heading:"Remote playback and download",paragraphs:["Playback requests older footage from supported storage. The user selects a device, channel and time window; the DVR must be online and the footage must not have been overwritten. Download may be slower than real time on a weak connection.","Export only what is necessary, keep the original where required and store downloaded copies securely." ]},
      {heading:"Choose the right action",paragraphs:["Use live view for a proportionate current check, playback for investigation, and download when a controlled evidence copy is genuinely needed. If the device is offline, wait for reconnection or retrieve the local storage through an authorised process."],bullets:["Live: current situational view","Playback: search an earlier event","Download: retain or share a controlled copy","Local export: fallback when remote transfer is unsuitable"]}
    ],faqs:[["Does live view record to the cloud?","Not automatically. The DVR normally records locally; any server storage must be expressly configured."],["Can I play back footage while the DVR is offline?","Normally not through CMSV6. The DVR must reconnect, or the local storage must be accessed through an authorised method."],["Why is remote playback slow?","Upload speed, mobile signal, channel quality, simultaneous users and DVR performance can all affect playback."],["Can downloaded footage be emailed?","Only if lawful, necessary and secure. Large or sensitive footage should use an approved controlled transfer method."]],related:[["What is CMSV6?","/resources/what-is-cmsv6"],["Device offline guide","/resources/cmsv6-troubleshooting-device-offline"],["Support","/support"]],published,reviewed:published
  },
  {
    section:"resources",slug:"cmsv6-gps-tracking-guide",title:"CMSV6 GPS Tracking Explained | Live Location & History",description:"Learn how compatible CMSV6 GPS reporting works, what affects location updates, how video adds context and why GPS accuracy and connectivity can vary.",eyebrow:"GPS guide",h1:"CMSV6 GPS tracking explained",intro:"Compatible GPS-enabled DVRs can report location, direction, journey status and history through CMSV6. GPS and mobile data perform different jobs: GPS estimates position, while the internet connection sends that information to the platform.",definition:"CMSV6 GPS tracking receives location reports from a compatible GPS-enabled DVR and presents them to authorised users alongside device and video information where configured.",takeaways:["GPS needs a suitable antenna view and compatible device configuration.","Mobile data is required to send updates remotely, even when the GPS receiver has a position.","Location is supporting information and is not guaranteed to be continuously available or perfectly accurate."],
    sections:[
      {heading:"How a location update reaches CMSV6",paragraphs:["The DVR receives satellite signals through its GPS antenna, calculates a position and passes the report through its internet connection. The CMSV6 server associates it with the correct device and authorised account."],bullets:["GPS antenna receives satellite signals","DVR calculates and timestamps a position","Mobile data, Wi-Fi or wired internet sends the report","CMSV6 displays supported current and historical information"]},
      {heading:"Why a position may be delayed or inaccurate",paragraphs:["Buildings, metal roofs, tunnels, covered yards, poor antenna placement, damaged cables, device power and configuration can affect GPS. A separate weak mobile connection can delay an otherwise valid position reaching CMSV6." ]},
      {heading:"Video plus journey context",paragraphs:["A location and timestamp can help identify which vehicle or mobile asset was near an event. Compatible camera footage can add road or operational context. Neither source should be treated as infallible; review time settings, signal quality and the original recording." ]},
      {heading:"Responsible location monitoring",paragraphs:["Tell drivers and other affected people when location is collected, why it is needed, who can see it and how long it is retained. Limit monitoring during private use and remove access when a role changes. GPS does not guarantee theft recovery and CMSV6 is not an emergency tracking service." ]}
    ],faqs:[["Does every CMSV6 device include GPS?","No. The DVR, GPS antenna and configuration must support it."],["Why does video work but GPS not update?","The DVR may have internet access while the GPS antenna lacks a valid fix, is disconnected or is not configured correctly."],["Can GPS work without mobile data?","The receiver may calculate a local position, but CMSV6 needs a supported internet connection to receive remote updates."],["Is the map position guaranteed to be exact?","No. Accuracy and update timing vary with equipment, antenna conditions, signal and configuration."]],related:[["Vehicle CCTV","/solutions/vehicle-cctv"],["Fleet CCTV","/solutions/fleet-cctv-and-video-telematics"],["Support","/support"]],published,reviewed:published
  },
  {
    section:"resources",slug:"cmsv6-device-activation-guide",title:"CMSV6 Device Activation Guide | Compatibility to First Login",description:"Prepare and activate a compatible CMSV6 DVR: collect device details, confirm connectivity, configure cameras and GPS, test local recording and complete remote checks.",eyebrow:"Activation guide",h1:"How to prepare a device for CMSV6 activation",intro:"Activation starts with compatibility, not account creation. iCustodian needs the exact device and connection details before a recorder can be configured safely for the correct CMSV6 service.",definition:"CMSV6 activation is the controlled process of confirming a compatible DVR, configuring its connection and account, and testing the remote functions supported by that installation.",takeaways:["Record the exact model and firmware before changing settings.","Confirm local recording and camera views before troubleshooting remote access.","Never publish device IDs, server credentials or administrator passwords."],
    sections:[
      {heading:"Information to prepare",paragraphs:["Provide manufacturer, exact model, firmware, channel count, installed cameras, connection type, GPS requirement and the remote functions needed. Send device identifiers only through the approved private support route."],bullets:["Manufacturer and model","Firmware version","Camera channel count and video standard","4G, Wi-Fi or wired connection","GPS, audio, playback and download needs","Number of users and sites"]},
      {heading:"Check the installation first",paragraphs:["Verify stable power, local recording, correct time and date, healthy storage and every required camera view. Fit the appropriate SIM, antennas or network cable and confirm that the connection has adequate data and signal." ]},
      {heading:"Configuration and account setup",paragraphs:["After compatibility is confirmed, iCustodian can supply the approved server and account information for that service. Use unique credentials, restrict permissions and keep administrator details out of public messages." ]},
      {heading:"First acceptance test",paragraphs:["Test live video, channel names, playback, GPS, device online state and any supported audio or events. Then disconnect the internet briefly only where safe to confirm local recording behaviour and reconnection. Record the final configuration for support." ]}
    ],faqs:[["Can I activate a device without checking compatibility?","No activation should be promised until the exact model, firmware and required functions are verified."],["Where do I find the login address?","Use only the approved access information supplied for your account; contact CMSV6 support if it is missing."],["Does activation include installation?","Not unless installation is expressly included in the order or quotation."],["When does the two-month free period apply?","It applies to qualifying compatible iCustodian DVRs purchased directly through iCustodian, subject to the offer terms."]],related:[["Manual compatibility checker","/cmsv6-device-compatibility"],["How CMSV6 works","/how-it-works"],["Contact support","/contact?enquiry=activation"]],published,reviewed:published
  },
  {
    section:"resources",slug:"cmsv6-troubleshooting-device-offline",title:"CMSV6 Device Offline? Connection Troubleshooting Guide",description:"Work through safe checks when a CMSV6 device is offline: power, local recording, SIM data, signal, antennas, network status and recent changes.",eyebrow:"Troubleshooting",h1:"Why is my CMSV6 device offline?",intro:"An offline status means CMSV6 is not currently receiving the expected connection from the compatible device. It does not necessarily mean that the DVR has stopped recording locally.",definition:"A CMSV6 device appears offline when its expected server connection is unavailable because of power, network, data, signal, configuration or equipment conditions.",takeaways:["First confirm whether the DVR still has power and records locally.","Check the connection before resetting or changing server settings.","Record the time, symptoms and recent changes before contacting support."],
    sections:[
      {heading:"Safe first checks",paragraphs:["Look for normal DVR power and recording indicators. Confirm the cameras still display locally and storage has no warning. Then check the router, SIM, Wi-Fi or wired connection used by the device."],bullets:["DVR power and local display","Recording and storage status","SIM data allowance and service","Mobile signal or network link","Antenna and cable connections","Recent power, firmware or configuration changes"]},
      {heading:"Separate local recording from remote access",paragraphs:["The DVR can continue recording to healthy local storage even when its CMSV6 connection is down. Do not remove storage or factory-reset the device merely because the remote platform shows offline." ]},
      {heading:"Mobile-data checks",paragraphs:["Confirm the SIM is active, has data allowance, uses the correct APN where required and can register on the network. A signal indicator alone does not prove that the device can reach the internet. Check antennas for damage and avoid enclosing them behind heavy metal." ]},
      {heading:"When to contact support",paragraphs:["Contact support if local recording has stopped, storage reports an error, the device repeatedly reconnects, settings were changed or the connection remains offline after basic checks. Provide the model, approximate last-online time and observations through the private support form—never post credentials publicly." ]}
    ],faqs:[["Will an offline DVR lose all footage?","Not normally. Local recording can continue while the remote connection is unavailable, provided the DVR has power and healthy storage."],["Should I factory-reset the DVR?","No. Do not reset or change advanced server settings unless CMSV6 support instructs you to do so."],["Why does the SIM show signal but CMSV6 stay offline?","The SIM may lack data, use the wrong APN, have restricted service or be unable to reach the server despite registering on a mobile network."],["What should I send support?","Send the model, connection type, last-online time, visible warnings and recent changes. Do not send passwords in an ordinary message."]],related:[["CMSV6 support","/support"],["Live viewing versus playback","/resources/live-cctv-versus-recorded-playback"],["Contact technical support","/contact?enquiry=support"]],published,reviewed:published
  }
] as const;

export const allSeoContent = [...solutionPages, ...resourcePages] as const;

export function getSeoContent(section:string,slug:string){
  return allSeoContent.find(page=>page.section===section&&page.slug===slug);
}
