/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CTA, Disclaimer, PricingCards, SectionHeading } from "../components";
import { EnquiryForm, PriceEstimator } from "../interactive";
import { faqs, features, industries, pageMeta, resources, steps } from "../site-data";

export function generateStaticParams() { return Object.keys(pageMeta).map(slug => ({ slug })); }

export async function generateMetadata({ params }: { params: Promise<{slug:string}> }): Promise<Metadata> {
  const { slug } = await params; const meta = pageMeta[slug]; if (!meta) return {};
  return { ...meta, alternates:{ canonical:`https://cmsv6.co.uk/${slug}` }, openGraph:{title:meta.title,description:meta.description,url:`https://cmsv6.co.uk/${slug}`} };
}

const heroCopy: Record<string,[string,string,string]> = {
  features:["Platform features","Remote monitoring that helps you see, locate and respond.","Explore the CMSV6 capabilities available through compatible equipment and the right configuration."],
  solutions:["Solutions for almost any environment","Moving, fixed, temporary or remote — keep the right view.","From one private vehicle to national fleets and multiple commercial sites, CMSV6 adapts to the equipment and setting."],
  "how-it-works":["Simple, connected monitoring","From compatible camera to your screen.","Understand how local recording, internet connectivity and UK-hosted CMSV6 access work together."],
  equipment:["Compatible iCustodian® equipment","Choose the right DVR for the job.","Connect CMSV6 with approved mobile DVRs, dash cameras, CCTV systems, cameras and accessories."],
  pricing:["CMSV6 server hosting","Clear prices. Flexible terms. Per compatible device.","Start with two months free when you purchase a compatible iCustodian DVR, then choose a plan that fits."],
  support:["CMSV6 customer support","Practical help from setup to playback.","Find clear first steps for activation, connectivity, account access and troubleshooting."],
  about:["About iCustodian CMSV6","Specialist CCTV products with a connected service.","CMSV6 is part of the wider iCustodian ecosystem for vehicle cameras, CCTV, DVRs and remote monitoring."],
  contact:["Contact & quotations","Tell us what you need to see.","Ask about subscriptions, activation, compatibility, renewals, support or a tailored multi-device system."],
  faq:["Frequently asked questions","Straight answers before you connect.","Understand compatibility, connectivity, storage, pricing and responsible use without the jargon."],
  resources:["CMSV6 resources","Practical guides for better remote visibility.","Learn how CMSV6, compatible DVRs, connectivity and responsible monitoring fit together."],
  privacy:["Legal information","Privacy information.","How personal information submitted through this website should be handled."],
  terms:["Legal information","Website and service terms.","Important terms for using this website and enquiring about CMSV6 services."],
  "responsible-use":["Responsible monitoring","Use CCTV, audio and GPS fairly.","Practical principles for lawful, transparent, necessary, proportionate and secure monitoring."],
};

export default async function StandardPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const hero=heroCopy[slug]; if(!hero) notFound();
  return <main><PageHero eyebrow={hero[0]} title={hero[1]} text={hero[2]}>{slug === "pricing" && <a className="button primary" href="#plans">See hosting plans</a>}{slug === "contact" && <a className="button primary" href="#enquiry">Start an enquiry</a>}</PageHero>{renderPage(slug)}{!["contact","privacy","terms","responsible-use"].includes(slug) && <CTA/>}</main>;
}

function PageHero({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children?:React.ReactNode}) { return <section className="page-hero"><div className="page-grid-bg"/><div className="container"><div className="breadcrumbs"><a href="/">Home</a><span>/</span><b>{eyebrow}</b></div><span className="eyebrow light-blue">{eyebrow}</span><h1>{title}</h1><p>{text}</p>{children && <div className="hero-actions">{children}</div>}</div></section>; }

function renderPage(slug:string) {
  switch(slug) {
    case "features": return <><section className="section"><div className="container"><SectionHeading eyebrow="Core capabilities" title="Live, locate, review and manage." text="Each feature is available where supported by the connected equipment and configuration."/><div className="feature-grid detailed">{features.map((f,i)=><article className="feature-card" key={f.title}><span className="feature-icon">{f.icon}</span><small>0{i+1}</small><h3>{f.title}</h3><p>{f.text}</p></article>)}</div><Disclaimer/></div></section><section className="section pale"><div className="container two-column"><div><h2>Local recording. Remote connectivity.</h2><p>A compatible DVR records footage to its installed local storage. CMSV6 provides remote access while the DVR has a suitable connection. If mobile data or Wi-Fi drops, local recording does not necessarily stop; live viewing and remote requests resume when connectivity returns, depending on the setup.</p></div><div className="info-card"><h3>Flexible access</h3><ul className="tick-list dark-ticks"><li>Supported web browser</li><li>Windows desktop client</li><li>Mobile application</li><li>Phone, tablet, laptop or desktop</li></ul><p className="small">Approved download links will be added only after exact application and server compatibility is confirmed.</p></div></div></section></>;
    case "solutions": return <><section className="section"><div className="container"><SectionHeading eyebrow="Across every environment" title="One monitoring platform, many practical uses." text="Choose the view, connectivity and compatible equipment around the environment — not the other way around."/><div className="solution-list">{industries.map((item,i)=><article key={item.title}><div className="solution-image" style={{backgroundImage:`url(${item.image})`}}/><div><span className="eyebrow">0{i+1} · {item.label}</span><h2>{item.title}</h2><p>{item.text}</p><ul>{solutionBullets[i].map(x=><li key={x}>{x}</li>)}</ul><a className="text-link" href="/contact">Discuss this solution →</a></div></article>)}</div></div></section><ResponsibleSector/></>;
    case "how-it-works": return <><section className="section"><div className="container"><SectionHeading eyebrow="Six steps" title="A clear path from equipment to remote visibility." text="Your exact data path and features depend on the installed system."/><div className="vertical-steps">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></article>)}</div><div className="data-path large-path"><span>Camera</span><b>→</b><span>DVR</span><b>→</b><span>Internet connection</span><b>→</b><span className="active">UK-hosted CMSV6</span><b>→</b><span>Phone, tablet or computer</span></div><Disclaimer/></div></section></>;
    case "equipment": return <EquipmentPage/>;
    case "pricing": return <PricingPage/>;
    case "support": return <SupportPage/>;
    case "about": return <AboutPage/>;
    case "contact": return <ContactPage/>;
    case "faq": return <FaqPage/>;
    case "resources": return <ResourcesPage/>;
    case "privacy": return <LegalPage type="privacy"/>;
    case "terms": return <LegalPage type="terms"/>;
    case "responsible-use": return <ResponsibleUse/>;
    default: return null;
  }
}

const solutionBullets = [
  ["Private cars, taxis and school transport","Delivery, haulage and logistics fleets","Emergency, security and public-service vehicles","Heavy plant, machinery and mobile workshops"],
  ["Homes, garages and outbuildings","Shops, offices and warehouses","Factories, depots and multi-branch businesses","Temporary sites and remote properties"],
  ["Livestock areas, barns and stables","Gates, fields, machinery and stores","Greenhouses, forestry and fisheries","Remote checks that can reduce unnecessary travel"],
  ["Boats, harbours and marine storage","Schools, campuses and authorised transport","Healthcare sites and patient transport","Utilities, events and temporary control locations"],
];

function ResponsibleSector(){ return <section className="section responsible"><div className="container"><SectionHeading eyebrow="Sensitive settings" title="Monitoring must be authorised, proportionate and appropriate." text="Schools, care settings, workplaces and public-service operations need particularly careful governance." light/><div className="responsible-grid"><article><h3>Education & care</h3><p>Use only for authorised safeguarding, transport, access or property-security purposes. Never monitor toilets, changing areas, private treatment spaces or other inappropriate locations.</p></article><article><h3>Workplace & transport</h3><p>Be transparent about driver, employee, passenger, audio and location monitoring. Respect private use and restrict access to people with a legitimate need.</p></article><article><h3>Public-facing systems</h3><p>Use appropriate signage and privacy information. Keep recordings secure, set suitable retention rules and provide a way for people to exercise applicable rights.</p></article></div></div></section> }

function EquipmentPage(){
  const products=[
    {
      name:"iCustodian® iC9800MDVR-AI",
      subtitle:"Hybrid GPS, 4G and Wi-Fi AI Mobile DVR",
      spec:"4/8-channel · 4G · Wi-Fi · GPS · AI",
      price:"£249.00",
      image:"/iC9000MDVR-AI.png",
      alt:"Front view of the iCustodian iC9800MDVR-AI mobile DVR",
      summary:"An intelligent mobile CCTV recorder built for live monitoring as well as recording, with support for driver assistance, driver monitoring and blind-spot detection on compatible installations.",
      features:["ADAS and driver monitoring","Blind-spot detection support","Cars, lorries and marine use","Homes and business premises"],
      url:"https://www.icustodian.com/product/icustodian-ic9800mdvr-ai-hybrid-gps-4g-wifi-mobile-dvr/"
    },
    {
      name:"iCustodian® iC9800MDVR-K",
      subtitle:"Hybrid 4G, Wi-Fi and GPS HD Mobile DVR",
      spec:"4/8-channel · 4G · Wi-Fi · GPS · HD",
      image:"/iC9800MDVR-K.png",
      alt:"Front view of the iCustodian iC9800MDVR-K key-lock mobile DVR",
      summary:"A robust hybrid recorder with password protection, video encryption and a key-lockable 2.5-inch SATA hard-drive housing for professional fixed or mobile surveillance.",
      features:["Key-lock storage protection","Password and video encryption","Up to eight camera channels","Vehicles, boats and fixed sites"],
      url:"https://www.icustodian.com/product/ic9800mdvr8-k/"
    },
    {
      name:"iCustodian® iC-N9DASHCAM",
      subtitle:"Compact 4-channel Hybrid MDVR Dash Camera",
      spec:"4-channel · 4G LTE · Wi-Fi · GPS · ADAS · DMS",
      image:"/N9.png",
      alt:"Angled view of the iCustodian iC-N9DASHCAM hybrid mobile DVR",
      summary:"A professional four-channel MDVR in a compact dashcam body, combining dual built-in 1080p cameras with support for two additional 1080p CCTV cameras and remote live streaming.",
      features:["Dual built-in 1080p cameras","Two additional camera inputs","Dual SD storage and encryption","ADAS and driver monitoring"],
      url:"https://www.icustodian.com/product/n9dashcam"
    }
  ];

  return <>
    <section className="section equipment-catalogue"><div className="container">
      <SectionHeading eyebrow="Featured compatible equipment" title="Professional recorders ready for CMSV6 streaming." text="Compare three versatile iCustodian systems for vehicles, homes, businesses and specialist installations. Follow any product link for the full specification, availability and current purchase information."/>
      <div className="product-grid equipment-grid">{products.map((product)=><article className="equipment-product" key={product.name}>
        <div className="product-visual equipment-product-image"><img src={product.image} alt={product.alt} loading="lazy" decoding="async"/><span>CMSV6 ready</span></div>
        <div className="equipment-product-body"><span className="product-type">CMSV6 compatible</span><h2>{product.name}</h2><h3>{product.subtitle}</h3><b className="equipment-spec">{product.spec}</b>
          {product.price?<div className="equipment-price"><small>Product price</small><strong>{product.price}</strong></div>:<div className="equipment-price price-link"><small>Price &amp; availability</small><strong>See iCustodian</strong></div>}
          <p>{product.summary}</p><ul>{product.features.map(feature=><li key={feature}>{feature}</li>)}</ul>
          <a className="button dark" href={`${product.url}?utm_source=cmsv6.co.uk&utm_medium=referral&utm_campaign=compatible_equipment`} target="_blank" rel="noreferrer">View product on iCustodian <span aria-hidden="true">↗</span></a>
        </div>
      </article>)}</div>
      <div className="equipment-shop"><div><span className="eyebrow light-blue">More compatible choices</span><h2>Explore the wider iCustodian DVR range.</h2><p>Find a wide variety of DVRs and mobile recorders that can be configured for the CMSV6 streaming app, from compact vehicle systems to multi-camera installations.</p></div><a className="button light large" href="https://www.icustodian.com/product-category/dvr/?utm_source=cmsv6.co.uk&utm_medium=referral&utm_campaign=compatible_equipment_range" target="_blank" rel="noreferrer">Browse all compatible DVRs <span aria-hidden="true">↗</span></a></div>
      <Disclaimer/>
    </div></section>
    <section className="section pale"><div className="container contact-grid"><div><SectionHeading eyebrow="Already own a DVR?" title="Let us check compatibility." text="Send the manufacturer, model, device ID where available, connection type, camera count and the remote functions you need. We will check before confirming compatibility."/><ul className="tick-list dark-ticks"><li>No assumptions about third-party devices</li><li>No promise until the model is checked</li><li>Advice for mobile and fixed installations</li></ul></div><EnquiryForm compact/></div></section>
  </>
}

function PricingPage(){ return <><section className="section" id="free-offer"><div className="container promo-panel"><span className="promo-big">2</span><div><span className="eyebrow red">Included with a compatible iCustodian DVR</span><h2>Two months of CMSV6 hosting free.</h2><p>Use the introductory period to connect cameras, configure mobile data or Wi-Fi, test live viewing and GPS, and get familiar with playback. A paid hosting plan is required to continue after the free period.</p></div><a className="button primary" href="https://www.icustodian.com/product-category/dvr/?utm_source=cmsv6.co.uk&utm_medium=referral&utm_campaign=two_months_free" rel="noreferrer">View compatible DVRs</a></div></section><section className="section pale" id="plans"><div className="container"><SectionHeading eyebrow="Published hosting plans" title="Choose a term for each compatible device." text="Simple standard pricing, with tailored quotations for larger and longer requirements."/><PricingCards/><div className="pricing-explainer"><div><h3>What the price covers</h3><p>CMSV6 server hosting for one compatible device, remote platform access and setup guidance for the selected term.</p></div><div><h3>What is separate</h3><p>DVRs, cameras, installation, mobile data, local storage, optional licences and server-side video storage unless expressly included.</p></div><div><h3>Need more?</h3><p>Ask for a quotation for fleets, multiple locations, longer terms and specialist configuration. No unapproved discount is assumed.</p></div></div></div></section><section className="section"><div className="container two-column estimator-wrap"><div><SectionHeading eyebrow="Quick estimator" title="Estimate standard hosting." text="Change the device count and term to see the published-price total."/><PriceEstimator/></div><div className="quote-card"><span className="eyebrow light-blue">Fleet & multi-site</span><h2>Need a tailored quotation?</h2><p>Tell us how many compatible devices, cameras and locations you need to manage, and the hosting term you have in mind.</p><a className="button light" href="/contact?enquiry=fleet">Request a quotation</a></div></div></section></> }

function SupportPage(){ const topics=["New customer setup","Device activation","Login and password help","Adding a device","Mobile-data and Wi-Fi setup","GPS troubleshooting","Camera troubleshooting","Playback and video download","Device offline checks","App and desktop-client guidance","Hosting renewal","Manuals and downloads"]; return <><section className="section"><div className="container"><SectionHeading eyebrow="Support centre" title="Choose the area you need help with." text="Never share server credentials, administrator passwords or customer device IDs in a public message."/><div className="support-grid">{topics.map((x,i)=><a href="#troubleshooting" key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3><b>Get guidance →</b></a>)}</div></div></section><section className="section pale" id="troubleshooting"><div className="container two-column"><div><SectionHeading eyebrow="First checks" title="Device showing offline?" text="Work through these steps before changing settings."/><div className="faq-list compact-faq">{["Confirm the DVR still has power and is recording locally.","Check that the supported internet connection is active.","Check SIM data allowance, signal or Wi-Fi/network status.","Confirm antennas and approved cables are firmly connected.","Note any warning shown and the last time the device reported."].map((x,i)=><details key={x}><summary>{i+1}. {x}</summary><p>Record what you find and contact support before resetting or changing advanced settings. A connection loss does not necessarily stop normal local DVR recording.</p></details>)}</div></div><div className="support-contact" id="login"><span className="eyebrow light-blue">Existing customer?</span><h2>Account and login assistance</h2><p>The approved CMSV6 login address will be published here once exact server and application compatibility is confirmed. We will not guess or expose private access details.</p><a className="button light" href="/contact?enquiry=support">Contact support</a><a className="text-link light-link" href="tel:+447543025555">Call +44 (0) 7543 02 5555 →</a></div></div></section></> }

function AboutPage(){ return <><section className="section"><div className="container about-grid"><div><SectionHeading eyebrow="Part of the iCustodian ecosystem" title="CCTV products and connected monitoring, with UK-focused support." text="iCustodian Limited specialises in CCTV security products for vehicles, homes and businesses. CMSV6 extends compatible equipment with live video, GPS and remote management."/><p>iCustodian supports customers in choosing compatible systems, connecting approved equipment and understanding what each configuration can provide. The service is designed for individual customers as well as businesses and larger organisations.</p><div className="stat-row"><div><b>UK</b><span>service focus</span></div><div><b>1:1</b><span>customer guidance</span></div><div><b>Wide</b><span>use-case range</span></div></div></div><div className="about-panel"><span>iCustodian®</span><h2>Smart security solutions for every space.</h2><p>Compatible equipment, clear advice and a practical route from local CCTV recording to remote visibility.</p><a className="button light" href="https://www.icustodian.com/about-us/?utm_source=cmsv6.co.uk&utm_medium=referral" rel="noreferrer">Visit iCustodian</a></div></div></section><section className="section pale"><div className="container values-grid"><article><span>01</span><h3>Clear compatibility</h3><p>Check equipment, connections and requirements before making a recommendation.</p></article><article><span>02</span><h3>Useful explanations</h3><p>Translate live view, local recording, GPS and remote playback into practical language.</p></article><article><span>03</span><h3>Responsible monitoring</h3><p>Keep privacy, access control, transparency and proportionality visible throughout the journey.</p></article></div></section></> }

function ContactPage(){ return <section className="section" id="enquiry"><div className="container contact-grid"><div><SectionHeading eyebrow="Talk to the UK team" title="A short enquiry is enough to get started." text="Choose the closest enquiry type and tell us what you already know. We can ask the right follow-up questions."/><div className="contact-options"><a href="tel:+447543025555"><span>Telephone</span><b>+44 (0) 7543 02 5555</b><small>Monday to Friday · 10am–8pm</small></a><a href="mailto:info@icustodian.com"><span>Email</span><b>info@icustodian.com</b><small>Subscriptions, compatibility and support</small></a><div><span>Head office</span><b>Holly Hill Road</b><small>Erith, Greater London, United Kingdom</small></div></div><p className="small">Do not submit passwords, administrator credentials, private server addresses or unnecessary personal information.</p></div><EnquiryForm/></div></section> }

function FaqPage(){ const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}; return <section className="section"><div className="container faq-layout"><div><span className="eyebrow">Answers by topic</span><h2>Before you choose a plan</h2><p>These answers explain the general service. Your exact options still depend on compatible equipment and configuration.</p><a className="button dark" href="/contact?enquiry=compatibility">Ask about my setup</a></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></div></section> }

function ResourcesPage(){ return <section className="section"><div className="container"><SectionHeading eyebrow="Learning centre" title="Make a more informed monitoring decision." text="Initial practical guides for individuals, installers and organisations."/><div className="resource-grid">{resources.map((r,i)=><article key={r}><span>{["Explainer","Use case","Buyer guide","Rural guide","Video guide","Responsible use"][i]}</span><h2>{r}</h2><p>{["A plain-English introduction to the CMSV6 platform and compatible equipment.","How one connected platform can support moving and fixed locations.","The practical questions to ask before selecting DVR hardware.","Remote checks for livestock, buildings, entrances and equipment.","Understand what is live, local and remotely retrievable.","Transparency, proportionality, retention and authorised access."][i]}</p><a href="/contact">Ask a related question →</a></article>)}</div></div></section> }

function LegalPage({type}:{type:"privacy"|"terms"}){ return <section className="section"><article className="container legal-content"><div className="legal-warning"><strong>Review required before publication</strong><p>This page is a structured placeholder, not legal advice. It must be completed and approved by an appropriately qualified UK legal or data-protection professional.</p></div>{type==="privacy"?<><h2>Privacy information framework</h2><p>iCustodian Limited should explain what personal information the CMSV6 website collects, why it is needed, the lawful basis for each use, how long it is retained, who receives it and how people can exercise applicable rights.</p><h3>Information submitted by visitors</h3><p>Contact and compatibility forms may collect names, business details, contact information, device details and enquiry content. Only information necessary to answer or manage the enquiry should be requested.</p><h3>Website information</h3><p>Essential technical records may be processed to operate, protect and troubleshoot the website. Optional analytics or advertising technologies should only be enabled in line with the published cookie choice and applicable law.</p><h3>Contact</h3><p>Privacy enquiries may be directed to <a href="mailto:info@icustodian.com">info@icustodian.com</a>. Final controller details, retention periods, processors, transfers, rights and complaint routes must be legally verified before publication.</p></>:<><h2>Terms framework</h2><p>These terms should distinguish clearly between website information, CMSV6 server hosting, compatible hardware, installation, mobile-data services, local recording and any separately purchased storage or support.</p><h3>Service availability</h3><p>Live viewing and GPS reporting require compatible equipment and suitable connectivity. Features, quality and availability depend on hardware, firmware, sensors, permissions, signal and configuration.</p><h3>Acceptable use</h3><p>Customers must use video, audio and location monitoring lawfully, fairly, transparently, securely and only for appropriate purposes. CMSV6 is not an emergency-response service and does not guarantee the prevention or detection of crime, loss or damage.</p><h3>Commercial terms</h3><p>Final subscription, renewal, cancellation, payment, support, service-level, liability and data-processing terms must be confirmed and legally approved before taking orders.</p></>}</article></section> }

function ResponsibleUse(){ return <section className="section"><div className="container responsible-page"><div className="legal-warning"><strong>Professional review required</strong><p>This practical overview does not guarantee compliance and is not a substitute for legal, safeguarding or data-protection advice.</p></div><SectionHeading eyebrow="Core principles" title="Monitor only what is justified." text="Customers are responsible for the lawful placement, configuration and use of every camera, microphone, sensor and tracking device."/><div className="principle-grid">{[["Lawful","Identify a valid purpose and lawful basis before monitoring."],["Fair & transparent","Tell affected people what is monitored, why and by whom."],["Necessary","Use monitoring only where the aim cannot reasonably be met in a less intrusive way."],["Proportionate","Limit cameras, audio, tracking, users and retention to what the purpose requires."],["Secure","Protect accounts, devices, recordings and downloads from unauthorised access."],["Accountable","Document decisions, reviews, access and deletion arrangements."]].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div><h2>Areas needing extra care</h2><div className="warning-list"><p><b>Employee and driver monitoring:</b> be clear about monitoring during work and private use, and avoid excessive or continuous observation without strong justification.</p><p><b>Audio:</b> sound monitoring is often more intrusive than video. Do not enable it by default; assess necessity, permissions and notice.</p><p><b>Children and vulnerable people:</b> schools, nurseries, hospitals and care services must apply safeguarding, privacy and sector-specific rules.</p><p><b>Public and neighbouring areas:</b> position cameras carefully, minimise unnecessary capture and provide clear signage and privacy information.</p><p><b>Biometric or AI features:</b> obtain specialist advice before using face recognition or other biometric processing.</p></div></div></section> }
